### ISSUE TITLE
Error while downloading results from ASReview LAB

### ISSUE THREAD

**Issue by SagevdBrand** [asreview/asreview#0]
**Describe the bug**
When using the covid-19 plugin, I tried to download my results. However the following error popped up: "ValueError: The state file does not correspond to the given data file, please use another state file or dataset." Meaning that I was not able to download the results 😢 

**To Reproduce**
I used the 'CORD-19 2020 (v2021 03-29) plug in, but I was not patient enough, so I clicked it twice or more (cancelled the upload and tried again). Then I screened about 5 articles and then wanted to download the results. Which I also tried a few times, before I realized it was working on the download, but it was so big, it just took a while. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64579032/113837321-029e2180-978e-11eb-8af7-64614b9db031.png)

**Version information**
 - Microsoft Windows [Version 10.0.19041.867]
 - ASReview version 0.16

**Additional context**
I also posted the same question on the discussion board #544, where the solution was to [clean the project files](https://asreview.readthedocs.io/en/latest/intro/installation.html?highlight=clean#remove-temporary-files)

**Comment by Rensvandeschoot** [comment]
The issue has been resolved in https://github.com/asreview/asreview/discussions/544
