### ISSUE TITLE
search function to select relevant literature is not working!

### ISSUE THREAD

**Issue by Jafarsab22** [asreview/asreview#1015]
**Describe the bug**
*What happened? And what did you expect to happen?*
search function to select relevant literature is not working!

**To Reproduce**
Steps to reproduce the problem:

**Screenshots**

**Version information**
 - OS: [e.g. Windows]
 - ASReview version [e.g. 0.6.2]

**Additional context**

**Comment by Rensvandeschoot** [comment]
@Jafarsab22 Can you add more information to the issue report? At least a screenshot of the error message in the front-end and the information in the CLI is needed to assist you further.

**Comment by J535D165** [comment]
Not reproducible. Feel free to reopen with more information.
