### ISSUE TITLE
search function to select relevant literature is not working!

### ISSUE THREAD

**Issue by Jafarsab22** [asreview/asreview#1017]
**Describe the bug**
*What happened? And what did you expect to happen?*
search function to select relevant literature is not working!

**To Reproduce**
Steps to reproduce the problem:
try searchin for any word when prompted for selecting relevant literature...you get an error: failed to load search results. 

**Screenshots**
see attached screen shot!

**Version information**
 - OS: [e.g. Windows]
 - ASReview version [e.g. 0.6.2]

**Additional context**
Add any other c
![WhatsApp Image 2022-03-28 at 3 54 54 PM](https://user-images.githubusercontent.com/66467042/160402770-dab06263-54a6-410b-b34c-f031feb1c783.jpeg)
ontext about the problem here.

**Comment by J535D165** [comment]
Can you share what you see on the command line? And would you mind sharing the dataset?

**Comment by Jafarsab22** [comment]
Hi I found the issue!!

It's because this file had in the first row "Article Title" instead of the required one "Title"….when I changed it, it worked! 

Thanks for your efforts anyway!

**Comment by J535D165** [comment]
Your welcome!
