### ISSUE TITLE
Add option to change hotkeys

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#1076]
Currently, the following hotkeys are available in ASReview. 

It would be nice to give users the option to select and change their hotkeys. Especially for different/international keyboards, this can be very useful. At the moment, ASReview LAB supports the following hotkeys:

```
While reviewing, you can press a key (or a combination of keys) to label a record as relevant or irrelevant, to return to the previous decision, or to add a note.

Press R or Shift + R:

Label a record as relevant

Press I or Shift + I:

Label a record as irrelevant

Press U or Shift + U:

Return to the previous decision

Press N or Shift + N:

Add a note
```

More hotkeys can also be added. 

💟  Added the help wanted tag to this feature request. We are welcoming contributions to this as we are not planning to work on this ourselves soon.

**Comment by Cathalijn** [comment]
Changing hotkeys may be useful for different and international keyboards, but especially for those used to working with other platforms it is crucial to prevent errors. For comparison, in Rayyan, I is for Include (ouch). They also have R for reaon for exclusion (ouch again). 
A T for tag would have added value when we want to start tagging, but I would start with an alternative to I and R: V for include and X for exclude.

**Comment by terrymyc** [comment]
> I like the V and X idea!! @terrymyc and @Rensvandeschoot what do you think?

I am fine with the idea. Maybe we can also allow users to customize the hotkeys. We may update our code using this [react-hotkeys-hook](https://github.com/JohannesKlauss/react-hotkeys-hook) npm package.

**Comment by Rensvandeschoot** [comment]
I agree!! Should we also update the front-end and change the hearts into V and X?

**Comment by Cathalijn** [comment]
After giving it some thought: particularly for the front-end V and X are conceptually better; we select based on inclusion and exclusion criteria (not on wether we like it or not)....
