### ISSUE TITLE
Missing settings metadata of a review in version 1.0

### ISSUE THREAD

**Issue by terrymyc** [asreview/asreview#1131]
When creating a new project in version 1.0, the `settings_metadata.json` in the `reviews` folder has empty items `model_param`, `query_param`, `feature_param`, and `balance_param`, and items `stop_if`, `n_prior_included`, `n_prior_excluded`, `abstract_only`, `as_data` are missing. Besides, `mode` is always `minimal`.

Instead, if you import and upgrade an old project, the items mentioned above have their values, and `mode` is `base`.

**Comment by J535D165** [comment]
Is this for oracle? or simulation?

> `mode` is always `minimal`

What do you mean? Mode?

**Comment by terrymyc** [comment]
Creating a project in any mode has this issue.

There is a key `mode` in the `settings_metadata.json`.

**Comment by J535D165** [comment]
```
% python -m json.tool ~/.asreview/oracle-metadata-test-1/reviews/1b0b1f4be11f4187b29eb9dbffaeaf6a/settings_metadata.json
{
    "settings": {
        "model": "nb",
        "query_strategy": "max",
        "balance_strategy": "double",
        "feature_extraction": "tfidf",
        "n_instances": 1,
        "mode": "minimal",
        "model_param": {},
        "query_param": {},
        "feature_param": {},
        "balance_param": {}
    },
    "state_version": "1",
    "software_version": "1.0rc3+52.g873070a.dirty",
    "model_has_trained": false
}
```

Oke let me try to study the issues one by one. The output above was created in v1 oracle, the `mode` is `minimal`. This is as expected, as the mode is the legacy mode. Options for this mode are: "minimal" (for oracle and explore), and "simulate" for simulations. Apperantly, there is also a "base" option. As this mode value is never as far as I know, we can remove it completely. I decided to give this a try in #1132.

**Comment by J535D165** [comment]
> items stop_if, n_prior_included, n_prior_excluded, abstract_only, as_data are missing.

> Instead, if you import and upgrade an old project, the items mentioned above have their values

The items on top are command line arguments (except from `abstract_only`). They should only be available for simulation projects. I will test this asap.

**Comment by J535D165** [comment]
Output for a simulation:

```
{
    "settings": {
        "model": "nb",
        "query_strategy": "max",
        "balance_strategy": "double",
        "feature_extraction": "tfidf",
        "n_instances": 1,
        "stop_if": "min",
        "n_prior_included": 1,
        "n_prior_excluded": 1,
        "model_param": {
            "alpha": 3.822
        },
        "query_param": {},
        "feature_param": {
            "ngram_max": 1,
            "stop_words": "english",
            "split_ta": 0,
            "use_keywords": 0
        },
        "balance_param": {
            "a": 2.155,
            "alpha": 0.94,
            "b": 0.789,
            "beta": 1.0
        }
    },
    "state_version": "1",
    "software_version": "1.0rc3+5.gf942f98.dirty",
    "model_has_trained": true
}
```
