### ISSUE TITLE
Pandoc installation required when rendering the docs

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview#1169]
When rendering the docs I obtain the following message:

```
Notebook error:
 PandocMissing in example_api_asreview_file.ipynb:
 Pandoc wasn't found.
 Please check that pandoc is installed:
 https://pandoc.org/installing.html
```

**Comment by PeterLombaers** [comment]
I managed to make it run by installing pandoc (https://github.com/jgm/pandoc/blob/master/INSTALL.md) and then running `pip install pandoc`. See also https://stackoverflow.com/questions/62398231/building-docs-fails-due-to-missing-pandoc

**Comment by J535D165** [comment]
It's requested by NBSphinx https://nbsphinx.readthedocs.io/en/0.2.15/installation.html#pandoc. Can be added to the docs somewhere.
