### ISSUE TITLE
Add feature: Highlight user defined keywords in title and abstract

### ISSUE THREAD

**Issue by darrennel** [asreview/asreview#1173]
## Feature Request

To help speed up the review process it would be very helpful if a user-defined set of keywords can be used to highlight text in the title and abstract, see image for example. Additionally, if the paper keywords can also be shown that would also be helpful. 

![image](https://user-images.githubusercontent.com/45100570/175449245-68fbe494-bbbb-4e2d-b0ea-2ba58e695f13.png)

**Comment by Rensvandeschoot** [comment]
Thank you for your suggestion! The implementation is provided by @[tomseinen](https://github.com/tomseinen) in https://github.com/asreview/asreview/discussions/995. Feel free to add to the discussion!
