### ISSUE TITLE
.txt not accepted as file format

### ISSUE THREAD

**Issue by lastoel** [asreview/asreview#1226]
**Describe the bug**
ASReview does not accept datasets in ` .txt` format and produces the following error:  ```ValueError: Cannot find proper encoding for data file.```

`.txt` is known not to be a currently [supported file format ](https://asreview.readthedocs.io/en/latest/data_format.html#tabular-file-format). This may be an issue for people who follow the instructions in the "Simulation LAB" exercises for downloading any of the Benchmark datasets or for other users working with their own `.txt` data. 

Simply changing the file extension to `.csv` once downloaded is enough to solve the problem. 

The question is if `.txt` can be included as a supported file format in the future. 

**To Reproduce**
1. Per the instructions in the "Simulation LAB" exercise: Go to the [overview with benchmark datasets](https://github.com/asreview/systematic-review-datasets#datasets), right-click on any of the ID's and click `Save Link As`. On some computers, the default format in which the dataset is then saved is `.txt`. The Hall_2012.txt data are included as an example: 
[Hall_2012.txt](https://github.com/asreview/asreview/files/9617273/Hall_2012.txt)

2. a) In the LAB interface: upload this file as a dataset for a new project. 
    b) In the CLI interface: run the following line of code from a directory containing a subfolder 'data' containing the data file and another subfolder called 'output':
```asreview simulate data/Hall_2012.txt --state_file output/txtresults.asreview --seed 123```

**Screenshots**
Download (benchmark) dataset by going through "Save link as": 
![image](https://user-images.githubusercontent.com/74184595/191526890-9ffb7c65-ea88-4f85-8428-41c8e5898818.png)

Resulting prompt for saving dataset in .txt format:
![image](https://user-images.githubusercontent.com/74184595/191527256-5eae8ad0-8a61-49da-b931-c04c9af10d83.png)

Error in LAB interface:
![image](https://user-images.githubusercontent.com/74184595/191525030-6dd8385d-f697-490b-8558-f8cfee49cdc0.png)

Error in CLI interface: 
![image](https://user-images.githubusercontent.com/74184595/191525217-5274f1f1-bb8b-4c6e-bd6c-18036e72f133.png)

**Version information**
 - OS: Windows 10 Enterprise
 - ASReview version 1.0

**Comment by J535D165** [comment]
Feel free to reopen or open a new issue if this remains an issue.

**Comment by Rensvandeschoot** [comment]
With the newly released SYNGERY dataset, the issue has been solved because downloading results in a CSV file instead of TXT file. See for example https://github.com/asreview/synergy-dataset/blob/master/datasets/Appenzeller-Herzog_2019/Appenzeller-Herzog_2019_ids.csv
