### ISSUE TITLE
RIS file of results doesn't download in version 0.19.1

### ISSUE THREAD

**Issue by vissereva** [asreview/asreview#1238]
Hi to you all,

I just finished screening and wanted to export my results as a RIS file. I then get an error message and cannot download the file. The error message says: '_The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()._' 

Does anyone know what I can do to still download a RIS file? Or how to convert one of the other options (Excel, tsv-utf 8 or csv-utf 8) to a RIS file so I can upload it in EndNote?

Steps to reproduce the problem:
End the screening of a project, click on the 'download results option', choose the RIS file option, click download.
(The error message isn't presented when exporting the results as an excel, tsv-utf 8 or csv-utf 8 file)

**Screenshots**
![2022-10-05](https://user-images.githubusercontent.com/97098641/194037828-b229717e-1663-4661-8a53-115b308dab3b.png)

**Version information**
 - OS: Windows 10
 - ASReview version 0.19.1

Thanks in advance!

**Comment by Rensvandeschoot** [comment]
The issue is discussed in https://github.com/asreview/asreview/issues/1099 and a fix is available in version 0.19.3. So, you might want to upgrade ASReview LAB to this version.

**Comment by vissereva** [comment]
Oh perfect, I couldn't find it in an earlier issue, but I must have overlooked it then. Thanks for the quick reply and solution!
