### ISSUE TITLE
Error message when trying to export a dataset from running ASReview on a server

### ISSUE THREAD

**Issue by markvaneck** [asreview/asreview#1250]
**Describe the bug**
When running ASReview on a server, I receive an error when I am trying to do an export. This error only shows when I want to export as a dataset, but not as a project. The following error message is shown:  
Failed to export the csv dataset. [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/asreview/webapp/projects/demo/tmpm9zb3r19/export_dataset.csv' Please try again.

**To Reproduce**
Select dataset when exporting a file when ASReview is running on a server, and then export. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47869770/197163923-c5c8be3e-6974-4758-a82d-cc3d34a2677e.png)

**Version information**
 - OS: Linux (not sure which distro)
 - ASReview version: 1.0

**Comment by Rensvandeschoot** [comment]
Could you try to upgrade to v1.0.3?

**Comment by markvaneck** [comment]
Thank you for the quick reply! I will relay the message to the party that hosts our server and I'll get back to you.

**Comment by Rensvandeschoot** [comment]
You can always extract the data from the `.asreview` file via the [API](https://asreview.readthedocs.io/en/latest/example_api_asreview_file.html)

**Comment by J535D165** [comment]
Is the path to the project folder adjusted? It looks like a very odd path to me. There shouldn't be data in that place. 

> Could you try to upgrade to v1.0.3?

I don't think this will solve the issue.

**Comment by markvaneck** [comment]
Firstly, apologies for the late follow-up. 

Secondly, @J535D165 was correct, Our hosting party had changed the location where projects were saved, because that was not a practical place for their server. He said he changed that via an `ASREVIEW_PATH` environment variable as per the documentation. After removing this, exporting projects is working as normal once again.

**Comment by J535D165** [comment]
I think the server admin set the environment variable to a relative path instead of an absolute path. Absolute paths are a better solution in my opinion. Therefore the projects were stored in the application folder (not a good idea because of upgrading!!). 

Please ensure that the admin sets up a backup properly. Feel free to ask questions here or on the discussion platform. Feel free to reopen this issue if there is something left to discuss.
