### ISSUE TITLE
Progress graph not updating past 186 records

### ISSUE THREAD

**Issue by bloodravenez** [asreview/asreview#1278]
**Describe the bug**
The progress graph has stopped updating after 186 records

**To Reproduce**
Review records past 186

**Screenshots**
![image](https://user-images.githubusercontent.com/119488012/204749491-97232565-4367-40e3-904d-ff570c837cfd.png)

**Version information**
Windows 11
 - ASReview version 1.1

**Comment by Rensvandeschoot** [comment]
Are you using the Oracle or SImulate mode? In the case you are using the simulate mode, you might want to refresh the results (see the button in the upper right corner)
