### ISSUE TITLE
Export only relevant articles

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#1323]
### Discussed in https://github.com/asreview/asreview/discussions/1322

<div type='discussions-op-text'>

<sup>Originally posted by **AKoert** February 21, 2023</sup>
Hi ASReview, 

I am very happy to use your software, as it makes the review process faster, thanks! Currently, we use ASReview as an initial screening method, in which we would like to switch to another software program to do an extensive selection with more authors. It would therefore be extremely helpful to be able to just export the articles I've marked as relevant. At the moment I am only able to export the entire dataset. 

Can someone help me with this?

Thanks in advance!</div>

**Comment by rohitgarud** [comment]
https://github.com/asreview/asreview/discussions/1322#discussioncomment-5072725

**Comment by rohitgarud** [comment]
I agree, this should be a part of core functionality.. But I am not well-versed in the frontend tech stack so will not be able to work on this much.. Thank you..
