### ISSUE TITLE
`setup.py` keywords should be array

### ISSUE THREAD

**Issue by jspaaks** [asreview/asreview#1349]
https://github.com/asreview/asreview/blob/9b776ba928e1a2279867a0266d5c244afbe937da/setup.py#L106

It looks like PyPI cuts the string at the spaces, thus generating 

- systematic
- review
- machine-learning

Screenshot PyPI:

![image](https://user-images.githubusercontent.com/4558105/226307685-3ce1cc54-6094-4196-ae32-7283d7f80c90.png)

**Comment by jspaaks** [comment]
Additionally, maybe we can use the same labels in the PyPI metadata as in the GitHub frontend: 

![image](https://user-images.githubusercontent.com/4558105/226346299-cf130d98-be01-41f6-8183-116018762690.png)

**Comment by J535D165** [comment]
Dear community, we are welcoming PRs.
