### ISSUE TITLE
webapp's `io.py` might clash with the standard library

### ISSUE THREAD

**Issue by jspaaks** [asreview/asreview#1350]
When I set up my PyCharm to do some development work on asreview, it generated confusing error messages because it recursively discovered `/asreview/webapp/io.py` which made the standard library's `io` not accessible anymore. The workaround was to set PyCharm's working directory to a directory that isn't a parent of `/asreview/webapp/io.py`,  but perhaps we should consider renaming `/asreview/webapp/io.py`.

**Comment by J535D165** [comment]
It is now integrated with `asreview/data`. Will be released in v2.0.
