### ISSUE TITLE
List of hyperparameters and their default values 

### ISSUE THREAD

**Issue by jspaaks** [asreview/asreview#1364]
I've extracted a list of hyperparameters and their default values. I'm copying the list below for future documentation. Probably some or most of the individual functions are already documented through the API docs (e.g. https://asreview.readthedocs.io/en/latest/generated/asreview.models.classifiers.LSTMBaseClassifier.html) but maybe there's value to having an overview as well?

code state: [9b776ba](https://github.com/asreview/asreview/tree/9b776ba928e1a2279867a0266d5c244afbe937da)

1. `query/random.py:35`
    1. `random_state=None`
1. `query/mixed.py:63`
    1. `strategy_1="max"`
    1. `strategy_2="random"`
    1. `mix_ratio=0.95`
    1. `random_state=None`
1. `query/mixed.py:175`
    1. `mix_ratio=0.95`
    1. `random_state=None`
1. `query/mixed.py:200`
    1. `mix_ratio=0.95`
    1. `random_state=None`
1. `query/cluster.py:43`
    1. `cluster_size=350`
    1. `update_interval=200`
    1. `random_state=None`
1. `balance/triple.py:69`
    1. `a=2.155`
    1. `alpha=0.94`
    1. `b=0.789`
    1. `beta=1.0`
    1. `c=0.835`
    1. `gamma=2.0`
    1. `shuffle=True`
    1. `random_state=None`
1. `balance/double.py:55`
    1. `a=2.155`
    1. `alpha=0.94`
    1. `b=0.789`
    1. `beta=1.0`
    1. `random_state=None`
1. `balance/undersample.py:39`
    1. `ratio=1.0`
    1. `random_state=None`
1. `feature_extraction/embedding_idf.py:68`
    1. `embedding_fp=None`
    1. `random_state=None`
1. `feature_extraction/tfidf.py:42`
    1. `ngram_max=1`
    1. `stop_words="english"`
1. `feature_extraction/base.py:28`
    1. `split_ta=0`
    1. `use_keywords=0`
1. `feature_extraction/sbert.py:69`
    1. `transformer_model='all-mpnet-base-v2'`
1. `feature_extraction/embedding_lstm.py:79`
    1. `loop_sequence=1`
    1. `num_words=20000`
    1. `max_sequence_length=1000`
    1. ` padding='post'`
    1. `truncating='post'`
    1. `n_jobs=1`
1. `feature_extraction/doc2vec.py:96`
    1. `vector_size=40`
    1. `epochs=33`
    1. `min_count=1`
    1. `n_jobs=1`
    1. `window=7`
    1. `dm_concat=0`
    1. `dm=2`
    1. `dbow_words=0`
1. `classifiers/nb.py:43`
    1. `alpha=3.822`
1. `classifiers/base.py:33`
    1. `-`
1. `classifiers/svm.py:45`
    1. `gamma="auto"`
    1. `class_weight=0.249`
    1. `C=15.4`
    1. `kernel="linear"`
    1. `random_state=None`
1. `classifiers/rf.py:44`
    1. `n_estimators=100`
    1. `max_features=10`
    1. `class_weight=1.0`
    1. `random_state=None`
1. `classifiers/logistic.py:45`
    1. `C=1.0`
    1. `class_weight=1.0`
    1. `random_state=None`
    1. `n_jobs=1`
1. `classifiers/lstm_base.py:93`
    1. `embedding_matrix=None`
    1. `backwards=True`
    1. `dropout=0.4`
    1. `optimizer="rmsprop"`
    1. `lstm_out_width=20`
    1. `learn_rate=1.0`
    1. `dense_width=128
    1. verbose=0`
    1. `batch_size=32`
    1. `epochs=35`
    1. `shuffle=False`
    1. `class_weight=30.0`
1. `classifiers/nn_2_layer.py:90`
    1. `dense_width=128`
    1. `optimizer='rmsprop'`
    1. `learn_rate=1.0`
    1. `regularization=0.01`
    1. `verbose=0`
    1. `epochs=35`
    1. `batch_size=32`
    1. `shuffle=False`
    1. `class_weight=30.0`
1. `classifiers/lstm_pool.py:97`
    1. `embedding_matrix=None`
    1. `backwards=True`
    1. `dropout=0.4`
    1. `optimizer="rmsprop"`
    1. `lstm_out_width=20`
    1. `lstm_pool_size=128`
    1. `learn_rate=1.0`
    1. `verbose=0`
    1. `batch_size=32`
    1. `epochs=35`
    1. `shuffle=False`
    1. `class_weight=30.0`

**Comment by J535D165** [comment]
It might be nice to integrate with `asreview algorithms`.
