### ISSUE TITLE
Consider adding linter information on the DEVELOPMENT.md file

### ISSUE THREAD

**Issue by abelsiqueira** [asreview/asreview#1367]
Add to the DEVELOPMENT.md:

- What to install
- What to run

It could maybe be a [pre-commit](https://pre-commit.com) as well?

**Comment by J535D165** [comment]
Improvements are welcome :) 

I think it is important to keep it readable for developers of all levels.

**Comment by jspaaks** [comment]
Additionally, I'd like to rename `DEVELOPMENT.md` to `README.dev.md`. I don't know if there is a standard name for this file, but I like that `README.dev.md` is directly next to the regular `README.md`, and the filename tells you what's in it.

**Comment by J535D165** [comment]
I think `DEVELOPMENT.md` is widely used. But in the end, it might be better to integrate it into the documentation itself. I like how pandas did this https://pandas.pydata.org/docs/development/contributing.html

**Comment by J535D165** [comment]
Fixed
