### ISSUE TITLE
 Feature Request: Exporting Datasets with Relevant, Irrelevant, and Unlabelled Records Separately

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview#1390]
**Issue Description:**
The recently merged PR [1335](https://github.com/asreview/asreview/pull/1335) added the ability to export only relevant records from the ASReview project. However, there have been user requests to also export a dataset containing irrelevant records. This issue proposes an enhancement that allows users to export different datasets

**Solution**
Modify the export functionality to support four separate datasets:

- Dataset containing all records
- Dataset containing relevant records
- Dataset containing irrelevant records
- Dataset containing unlabelled records

Update the frontend interface to provide the following options for exporting datasets:

- Export All Records (single dataset containing all records)
- Export Subsets of Records 

**Drawbacks:**

The frontend interface may become more complex due to the addition of multiple dataset export options. This may lead to an overwhelming number of options for users and a more cluttered interface. Also, technically it might be challenging to export three datasets. A solution might be to export a zip folder containing the three separate datasets with only relevant, irrelevant, and unlabelled records.

**Comment by J0hannn** [comment]
Did you find a solution on that one? I really need the unlabeld data option right now.  Sure workaround would be to just export all, import to Zotereo (or alike), sort by labeled/unlabeled, export unlabeled again. But its exhausting, especially with hugh datasets.

**Comment by Rensvandeschoot** [comment]
Different data exports will be integrated in version 2!
