### ISSUE TITLE
pkg_resources is deprecated as an API

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#1394]
It's time to update pkg_resources as it is deprecated. 

```
=================================================== warnings summary ===================================================
../../../.pyenv/versions/3.9.7/envs/asreview-dev/lib/python3.9/site-packages/pkg_resources/__init__.py:121
  /Users/Bruin056/.pyenv/versions/3.9.7/envs/asreview-dev/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
```

**Comment by J535D165** [comment]
This is an example implementation https://git.smhi.se/climix/climix/-/merge_requests/165/diffs

**Comment by jspaaks** [comment]
I don't mind taking a stab at this. While I'm at it, how would you like refactoring such that we are not loading our own functionality as if it is coming from a plugin. For example for balancers, it could look like this:

```python
from asreview.models.balance import DoubleBalance
from asreview.models.balance import SimpleBalance
from asreview.models.balance import TripleBalance
from asreview.models.balance import UndersampleBalance
from importlib.metadata import entry_points


def list_balancers():
    my_balancers = {b.name: b for b in [
        DoubleBalancer,
        NoneBalancer,
        TripleBalancer,
        UndersampleBalancer
    ]}
    group_name = "asreview.models.balance"
    try:
        other_balancers = {e.name: e.load() for e in entry_points(group=group_name)}
    except Exception as e:
        print("Something went wrong loading a module from entrypoint group " +
              f"'{group_name}'. The error message was: {e}\nContinuing...")
        other_balancers = {}
    d = dict()
    d.update(my_balancers)
    d.update(other_balancers)
    return dict(sorted(d.items()))
```

Code that uses `load_balancers` would then do:

```python
# need a class
Balancer = load_balancers()["double"]

# need an instance
balancer = load_balancers()["double"]()

# need a list of names
balancer_names = [k for k, v in load_balancers().items()]

# need a list of classes
balancer_classes = [v for k, v in load_balancers().items()]
```

This would obfuscate the need for the entrypoint groups in setup.py:

https://github.com/asreview/asreview/blob/d6062883c204651fd6ff719be69cc5df26fe7756/setup.py#L178-L183

Additionally it would obfuscate the need for some or all of the following functions:

1. `asreview.data.base.get_entry_points`
1. `asreview.datasets.get_entry_points`
1. `asreview.entry_points.algorithms.list_balance_strategies`
1. `asreview.entry_points.algorithms.list_classifiers`
1. `asreview.entry_points.algorithms.list_feature_extraction`
1. `asreview.entry_points.algorithms.list_query_strategies`
1. `asreview.entry_points.simulate.get_balance_model`
1. `asreview.entry_points.simulate.get_classifier`
1. `asreview.entry_points.simulate.get_feature_model`
1. `asreview.entry_points.simulate.get_query_model`
1. `asreview.io.utils._reader_class_from_entry_point`
1. `asreview.io.utils._writer_class_from_entry_point`
1. `asreview.io.utils.get_reader_class`
1. `asreview.io.utils.get_writer_class`
1. `asreview.io.utils.list_reader_names`
1. `asreview.io.utils.list_readers`
1. `asreview.io.utils.list_writer_names`
1. `asreview.io.utils.list_writers`
1. `asreview.list_readers`
1. `asreview.list_writers`
1. `asreview.models._list_classifiers`
1. `asreview.models.balance.get_balance_class`
1. `asreview.models.balance.get_balance_model`
1. `asreview.models.balance.list_balance_strategies`
1. `asreview.models.balance.utils._model_class_from_entry_point`
1. `asreview.models.balance.utils.get_balance_class`
1. `asreview.models.balance.utils.get_balance_model`
1. `asreview.models.balance.utils.list_balance_strategies`
1. `asreview.models.balance.utils.list_model_names`
1. `asreview.models.classifiers.get_classifier_class`
1. `asreview.models.classifiers.get_classifier`
1. `asreview.models.classifiers.list_classifiers`
1. `asreview.models.classifiers.utils._model_class_from_entry_point`
1. `asreview.models.classifiers.utils.get_classifier_class`
1. `asreview.models.classifiers.utils.get_classifier`
1. `asreview.models.classifiers.utils.list_classifiers`
1. `asreview.models.classifiers.utils.list_model_names`
1. `asreview.models.feature_extraction.get_feature_class`
1. `asreview.models.feature_extraction.get_feature_model`
1. `asreview.models.feature_extraction.list_feature_extraction`
1. `asreview.models.feature_extraction.utils._model_class_from_entry_point`
1. `asreview.models.feature_extraction.utils.get_feature_class`
1. `asreview.models.feature_extraction.utils.get_feature_model`
1. `asreview.models.feature_extraction.utils.list_feature_extraction`
1. `asreview.models.feature_extraction.utils.list_model_names`
1. `asreview.models.get_classifier_class`
1. `asreview.models.get_classifier`
1. `asreview.models.query.get_query_class`
1. `asreview.models.query.get_query_model`
1. `asreview.models.query.list_query_strategies`
1. `asreview.models.query.mixed.get_query_model`
1. `asreview.models.query.utils._model_class_from_entry_point`
1. `asreview.models.query.utils.get_query_class`
1. `asreview.models.query.utils.get_query_model`
1. `asreview.models.query.utils.list_model_names`
1. `asreview.models.query.utils.list_query_strategies`
1. `asreview.settings.get_balance_model`
1. `asreview.settings.get_classifier`
1. `asreview.settings.get_feature_model`
1. `asreview.settings.get_query_model`
1. `asreview.utils._model_class_from_entry_point`
1. `asreview.utils._reader_class_from_entry_point`
1. `asreview.utils._writer_class_from_entry_point`
1. `asreview.utils.get_entry_points`
1. `asreview.utils.list_model_names`
1. `asreview.utils.list_reader_names`
1. `asreview.utils.list_writer_names`

**Comment by rohitgarud** [comment]
The entrypoints and the groups allow us to develop extensions such as different models. How this will be handled in the above modification?

**Comment by jspaaks** [comment]
Hi Rohit, thanks for the question. Plugins would define a class, let's say `NewBalancer`, and in the plugin's `setup.py`  /`setup.cfg` / `pyproject.toml` it would point to this class, with syntax like

```python
"asreview.models.balance": [ 
     "new = asreview_plugin_balancer.models.balance:NewBalance" 
], 
```

Once the plugin is installed, `list_balancers` from the snippet above will pick up the new class when it gets to the line that says:

```python
other_balancers = {e.name: e.load() for e in entry_points(group=group_name)}
```

PS: I updated the snippet above because in the usage examples I had mistakenly used `load_balancers` instead of `list_balancers`. Sorry for the confusion.

**Comment by rohitgarud** [comment]
Thank you @jspaaks for the clarification. This means that the current way of creating extensions will not be affected by the modification you are proposing, it is how we are doing it now.

**Comment by jspaaks** [comment]
> This means that the current way of creating extensions will not be affected by the modification you are proposing, it is how we are doing it now.

That is my understanding as well, although I find it difficult to judge if there is code out there that makes use of any of the functions that will disappear by this change, so maybe that will lead to people having to update their imports and a small part of their code.

**Comment by rohitgarud** [comment]
I think @J535D165 is in a better position to comment on this. But I think the modification should not force users to change the code in the extensions or some personal scripts. That will be a breaking change.
