### ISSUE TITLE
Citation page in front-end

### ISSUE THREAD

**Issue by jteijema** [asreview/asreview#1402]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to see an extra page in the front-end with citation data. It should be as easy to use as possible. I have created a mockup of what the page could look like.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/28191416/231772842-66ca6334-41f8-4e59-9b3d-cfcf6305d6b6.png)

**Comment by Rensvandeschoot** [comment]
related to https://github.com/asreview/asreview/discussions/1403

**Comment by VeenDuco** [comment]
I'll go and try to find something for this issue to fix it.
