### ISSUE TITLE
Update dev dependencies with recent style additions?

### ISSUE THREAD

**Issue by jspaaks** [asreview/asreview#1411]
DEVELOPMENT.md was recently updated with dev dependencies for styling. It says to:

```shell
pip install black[jupyter] flake8 flake8-isort isort
```

Should we add this to the `dev` dependencies in setup.py?

https://github.com/asreview/asreview/blob/9b35dfbf42cc34e37dd4256f07d388daa2c80d3d/setup.py#L44-L52

(probably install `black` without the jupyter stuff )

**Comment by J535D165** [comment]
Sounds good!

**Comment by jspaaks** [comment]
PR was merged, closing
