### ISSUE TITLE
Exporting RIS-file from RefWorks

### ISSUE THREAD

**Issue by taleevenhuis** [asreview/asreview#1416]
1) I have a file from CINAHL / Embase which: 
a) I first imported into RefWorks; 
b) then re-exported as RIS. 
c) I reimported this file, exported from RefWorks, into ASReview. 
d) After adding prior knowledge, I again exported the file from ASReview as RIS.
e) Finally, I tried to import this file back into Refworks. This succeeded, but did not look neat in RefWorks.
Authors' names are spread over as many fields as there are characters and punctuation marks in the author field. See an example below.
Zotero doesn't give this problem.

How can this be resolved?

Kind regards, Tale Evenhuis (University of Applied Sciences Utrecht)

TY  - JOUR
ID  - RefID:8560-mizdrak2015differential
A1  - [
A1  - '
A1  - M
A1  - i
A1  - z
A1  - d
A1  - r
A1  - a
A1  - k
A1  - ,
A1  -  
A1  - A
A1  - n
A1  - j
A1  - a
A1  - '
A1  - ,
A1  -  
A1  - '
A1  - S
A1  - c
A1  - a
A1  - r
A1  - b
A1  - o
A1  - r
A1  - o
A1  - u
A1  - g
A1  - h
A1  - ,
A1  -  
A1  - P
A1  - e
A1  - t
A1  - e
A1  - r
A1  - '
A1  - ,
A1  -  
A1  - '
A1  - W
A1  - a
A1  - t
A1  - e
A1  - r
A1  - l
A1  - a
A1  - n
A1  - d
A1  - e
A1  - r
A1  - ,
A1  -  
A1  - W
A1  - i
A1  - l
A1  - m
A1  - a
A1  -  
A1  - E
A1  - .
A1  - '
A1  - ,
A1  -  
A1  - '
A1  - R
A1  - a
A1  - y
A1  - n
A1  - e
A1  - r
A1  - ,
A1  -  
A1  - M
A1  - i
A1  - k
A1  - e
A1  - '
A1  - ]
T1  - Differential Responses to Food Price Changes by Personal Characteristic: A Systematic Review of Experimental Studies
Y1  - 2015
VL  - 10
IS  - 7
SP  - 1
EP  - 19
N1  - ASReview_relevant
JF  - PLoS ONE
SN  - 1932-6203
UR  - https://search.ebscohost.com/login.aspx?direct=true&db=a9h&AN=108634050&site=ehost-live&scope=site 10.1371/journal.pone.0130320
M1  - Journal Article
AB  - Background: Fiscal interventions to improve population diet have been recommended for consideration by many organisations including the World Health Organisation and the United Nations and policies such as sugar-sweetened beverage taxes have been implemented at national and sub-national levels. However, concerns have been raised with respect to the differential impact of fiscal interventions on population sub-groups and this remains a barrier to implementation. Objective: To examine how personal characteristics (such as socioeconomic status, sex, impulsivity, and income) moderate changes in purchases of targeted foods in response to food and beverage price changes in experimental settings. Design: Systematic review Data Sources: Online databases (PubMed, EMBASE, Web of Science, EconLit and PsycInfo), reference lists of previous reviews, and additional data from study authors. Study Selection: We included randomised controlled trials where food and beverage prices were manipulated and reported differential effects of the intervention on participant sub-groups defined according to personal characteristics. Data Analysis: Where possible, we extracted data to enable the calculation of price elasticities for the target foods by personal characteristic. Results: 8 studies were included in the review. Across studies, the difference in price elasticity varied from 0.02 to 2.43 between groups within the same study. 11 out of the total of 18 comparisons of own-price elasticity estimates by personal characteristic differed by more than 0.2 between groups. Income related factors were the most commonly considered and there was an indication that own-price elasticity estimates do vary by income but the direction of this effect was not clear. Conclusion: Experimental studies provide an opportunity to examine the differential effects of fiscal measures to improve population diets. Patterns in price sensitivity by personal characteristics are complex. General conclusions pertaining to the effects of personal characteristics on price sensitivity are not supported by the evidence, which shows heterogeneity between studies and populations. Trial Registration: PROSPERO ABSTRACT FROM AUTHOR]; Copyright of PLoS ONE is the property of Public Library of Science and its content may not be copied or emailed to multiple sites or posted to a listserv without the copyright holder's express written permission. However, users may print, download, or email articles for individual use. This abstract may be abridged. No warranty is given about the accuracy of the copy. Users should refer to the original published version of the material for the full abstract. (Copyright applies to all Abstracts.)
PB  - Public Library of Science
DA  - 07/07
ER  -

**Comment by J535D165** [comment]
Can you show me an example RIS record from step c (after the export from RefWorks)?

We know that some tools aren't handling RIS well. Zotero is indeed one of the better solutions given the import and export of RIS files.

**Comment by taleevenhuis** [comment]
[12 records in RIS_CINAHL_export from RefWorks.txt](https://github.com/asreview/asreview/files/11352970/12.records.in.RIS_CINAHL_export.from.RefWorks.txt)

Hello Jonathan, thanks for picking up this question. In the attachments you will find a txt.file with 12 records from CINAHL, which have been first imported in RefWorks and subsequently have been exported from RefWorks, according to step c)

Regards, Tale!

**Comment by J535D165** [comment]
Looks like this issue: https://github.com/asreview/asreview/issues/1005. Also a temporary fix is proposed there.

**Comment by marcolaux** [comment]
> Looks like this issue: [#1005](https://github.com/asreview/asreview/issues/1005). Also a temporary fix is proposed there.

in the linked issue there is no fix that applies to this issue here

I also have it that the authors letters are scattered into seperate fields like in the OP here.
