### ISSUE TITLE
Bug with uploading dataset: ',' expected after '"'

### ISSUE THREAD

**Issue by SHBvanDijk** [asreview/asreview#1417]
**Describe the bug**
When uploading the csv-file I intend to screen, a bug appears: ',' expected after '"'
*What happened? And what did you expect to happen?*
The bug appeared and I could not proceed to selecting prior knowledge. I have never experienced this problem earlier when uploading datasets to ASReview, so I expected to be able to upload the file without any problems.

**To Reproduce**
Again upload the csv-file

**Screenshots**
![image](https://user-images.githubusercontent.com/100280266/235102943-67d734f1-9cc9-4fc5-a266-010c88bb5a33.png)

**Version information**
 - OS: Windows
 - ASReview version 0.17.1

**Comment by J535D165** [comment]
Looks like an issue with the CSV file. You can try to convert it to an XLSX file (in Excel for example) and try to import it. 

Also, it might be nice to update ASReview with `pip install --upgrade asreview` as we are in version 1.2 at them moment.

**Comment by SHBvanDijk** [comment]
Eventually, I could fix it by manually add the prior knowledge files (that is: included papers, this search is an update) in EndNote and exporting a refman .xml-file, I somehow discovered.
Thanks for the quick reply!
