### ISSUE TITLE
Create docker images for amd64

### ISSUE THREAD

**Issue by george-gca** [asreview/asreview#1449]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently there are only arm64 images on [docker hub](https://hub.docker.com/r/asreview/asreview/tags).

**Describe the solution you'd like**
An official `amd64` docker image.

**Teachability, Documentation, Adoption, Migration Strategy**
Will be easier to use in a shared environment where docker is allowed, but pip is not.

**Comment by abelsiqueira** [comment]
Hi @george-gca, due to the Docker Hub changes (see #1353), the images are now on `ghcr.io`: https://github.com/asreview/asreview/pkgs/container/asreview
