### ISSUE TITLE
Password protection on cloud

### ISSUE THREAD

**Issue by asheetal** [asreview/asreview#1459]
Working on cloud needs a password protect. Not always possible to access the container in cloud. Need something like 
```
sudo systemctl start asreview
```

Is this possible?

**Comment by J535D165** [comment]
Thanks for the question. Do you have a service file? Can you show it?

**Comment by asheetal** [comment]
I could not get very far. I was trying to the service file from rstudio-server. not sure if containers allow password protection. Anyway, at the moment this was just a hiccup in cloud. I can continue working on laptop, to get this running on cloud, would need some stronger security considerations.
