### ISSUE TITLE
ImportError: cannot import name 'metadata' from 'importlib'

### ISSUE THREAD

**Issue by acmdorio** [asreview/asreview#1481]
**Describe the bug**
ImportError: cannot import name 'metadata' from 'importlib'

**To Reproduce**
Steps to reproduce the problem:
- just install ASReview and try to run it (w/ Python<3.8).

**Version information**
 - OS: MacOS 13
 - ASReview version 1.2

**Additional context**

**Comment by J535D165** [comment]
Thanks for reporting. You are right. We will bump the minimum version to 3.7 in the next release (also because the version is EOL https://devguide.python.org/versions/). However, the current version should be fixed, so I thank you for your PR!

Duplicate #1418

**Comment by acmdorio** [comment]
Nice! My pleasure to collaborate.
BR,
*
--
ANDRÉ

**Comment by J535D165** [comment]
Fixed in https://github.com/asreview/asreview/releases/tag/v1.2.1 by bumping the minimum version of Python to 3.8.
