### ISSUE TITLE
Casting to sparse matrix in project.py

### ISSUE THREAD

**Issue by jteijema** [asreview/asreview#1487]
https://github.com/asreview/asreview/blob/25ce8540a9c7e006c100b0da3617bc342c3597d3/asreview/project.py#L390C1-L397C14

```python
if isinstance(feature_matrix, np.ndarray):
    feature_matrix = csr_matrix(feature_matrix)
if not isinstance(feature_matrix, csr_matrix):
    raise ValueError(
        "The feature matrix should be convertible to type "
        "scipy.sparse.csr.csr_matrix."
    )
```

We're casting all feature matrices to sparse matrix. This might be inefficient in some cases when compared to using a dense matrix. 

Why was this format chosen?

**Comment by J535D165** [comment]
Resolved in https://github.com/asreview/asreview/pull/1773. Feel free to reopen if you think otherwise.
