### ISSUE TITLE
Tensorflow 2.13.0 removes KerasClassifier wrapper

### ISSUE THREAD

**Issue by jteijema** [asreview/asreview#1494]
https://github.com/tensorflow/tensorflow/releases

TF 2.13.0 removed the Keras scikit-learn API wrappers (KerasClassifier and KerasRegressor), which had been deprecated in August 2021. We recommend using SciKeras instead.

This is a breaking change for our NN classifier.

Options right now:
- try to get it to work without a wrapper
- pin Tensorflow to 2.12.x
- use [adriangb/scikeras](https://github.com/adriangb/scikeras )

**Comment by J535D165** [comment]
Thanks for the issue. Option 1 is the best and looks straightforward. Would you like to help me?

**Comment by J535D165** [comment]
Users running into this problem can downgrade tensorflow. Fix in the next release.
