### ISSUE TITLE
Add Dataset throw an exception

### ISSUE THREAD

**Issue by jf29medma** [asreview/asreview#1516]
**Describe the bug**
Right now I wanted to try out the python API, following this simulation https://asreview.readthedocs.io/en/latest/simulation_api_example.html

When entering the 5th code an exception occured "BadFileFormatError". Normally I would expect that this line would add the dataset to the project. I tried using my own data that works in the ASReview lab, but it throws the same exception as in the example.

Lines of code: 
project.add_dataset("van_de_Schoot_2017.csv")

The full error:
![Screenshot 2023-08-21 075645](https://github.com/asreview/asreview/assets/142770314/9fafddf4-e224-49cc-af49-def0353c3591)

**Comment by Rensvandeschoot** [comment]
Thank you for reporting! What version of ASReview are you using??

**Comment by jf29medma** [comment]
I am using version 1.2.1

**Comment by jf29medma** [comment]
Hello,
I could not find a solution yet. Did it work for you when you follow the sample tutorial?

Thank you!

**Comment by jteijema** [comment]
@PeterLombaers We should update the API example

**Comment by jf29medma** [comment]
First of all thank you @jteijema 

Update: It worked for me doing the tutorial locally in VSC! Doing this with jupyter notebook I run into above mentioned issues, maybe there are some issues accessing data in my google drive. If I find a solution I will mention it here :D

**Comment by jteijema** [comment]
@jf29medma, glad to hear the tutorial worked for you in VSC. If you find a solution to the issues you encountered with Jupyter Notebook, please do share. It could be helpful for the community. 😊

**Comment by J535D165** [comment]
Thanks for reporting and the suggestion to use SYNERGY. SYNERGY would be the best solution. I made a quickfix for this example: 

```bash
curl https://raw.githubusercontent.com/asreview/systematic-review-datasets/metadata-v1-final/datasets/van_de_Schoot_2017/output/van_de_Schoot_2017.csv > tmp_data/api_simulation/data/van_de_Schoot_2017.csv
```
