### ISSUE TITLE
Importing RIS files from Embase

### ISSUE THREAD

**Issue by Emanuel-1986** [asreview/asreview#1521]
Hi,

The help of @Rensvandeschoot was greatly appreciated. 

I tried importing a RIS file into ASReview, which was directly exported from Embase. However, it gave the issue below:

![image](https://github.com/asreview/asreview/assets/143593753/fc08ce1e-d29f-4429-ae05-cabf43db98c5)

Then I tried the solution offered by https://github.com/asreview/asreview/issues/1005  by doing: Replace A1  -  by AU  - 

However, it still did not work:

![image](https://github.com/asreview/asreview/assets/143593753/25d6ca17-e959-4d0f-b624-872034971246)

Then, the RIS file was converted to .txt file, the author fields were kept as originally provided by Embase, but the sentence underneath each record, "Link to ..." was deleted. This revised .txt file was imported into ASReview, and it worked!

![image](https://github.com/asreview/asreview/assets/143593753/fcbc8b37-7c7a-41aa-b737-855476ebf57d)

So my request is how to delete this sentence (containing unique links for each record) automatically?

Here are the test datasets:

[EMBASE_original.txt](https://github.com/asreview/asreview/files/12496061/EMBASE_original.txt)

[EMBASE_author_field_replaced.txt](https://github.com/asreview/asreview/files/12496065/EMBASE_author_field_replaced.txt)

[EMBASE_sentence_removed.txt](https://github.com/asreview/asreview/files/12496067/EMBASE_sentence_removed.txt)

[EMABSE_AU_preserved_removed_sentence.txt](https://github.com/asreview/asreview/files/12496068/EMABSE_AU_preserved_removed_sentence.txt)

## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**
A clear explanation of how your new feature can be used by users.
Maybe with screenshot or design?

**Comment by Emanuel-1986** [comment]
Hi,

The solution to importing ris files from Embase to be used in ASReview.

Simply untick the URL and link before exporting the RIS file...

![WhatsApp Image 2023-09-01 at 10 57 27](https://github.com/asreview/asreview/assets/143593753/8c1f3845-2854-4d53-82b5-6c52b71a9d3f)

**Comment by Rensvandeschoot** [comment]
Thank you for reporting the issue and the fix!!
