### ISSUE TITLE
ASReview (Docker) Crashes on project creation when trying to select random or searching while adding prior knowledge

### ISSUE THREAD

**Issue by SamyAteia** [asreview/asreview#1571]
**Describe the bug**
ASReview started via Docker crashes and displays a blank, white screen when pressing the random button while trying to add prior knowledge during project creation. It also crashes when trying to execute a search in the add prior knowledge dialog.

**To Reproduce**
- Start ASReview as a Docker container as described here https://github.com/asreview/asreview/tree/master/Docker 
- Create a new project in simulation or exploration mode and select a benchmark dataset.
- Follow the creation screen into 2. -> "Add prior knowledge", click on Add and then click on Random or Click on search type in a search string and execute the search.

**Version information**
 - OS:  Windows, Docker
 - ASReview version: 1.3.1

**Additional context**
This happened both with the simple docker setup and with the docker-compose setup with authentication. I attached a log of the backend container from the docker setup with authentication:

[error.log](https://github.com/asreview/asreview/files/13264348/error.log)

**Comment by J535D165** [comment]
Sorry for inconvenience. I'm jumping on this one as well!

**Comment by J535D165** [comment]
I can't reproduce the issue for the simple Docker without authentication. I run the simple version with `docker run -p 8000:5000 ghcr.io/asreview/asreview:latest` on localhost:8000. I will try to run with auth later. 

The log seems to suggest an issue with the driver https://docs.sqlalchemy.org/en/20/errors.html#error-4xp6. Could you let me know if you're using a config file with Postgres setup?

**Comment by SamyAteia** [comment]
Hi @J535D165 thanks for jumping on this issue so quickly. I didn't use the latest released docker container from the repository but build my own by following the process described here: https://github.com/asreview/asreview/tree/master/Docker

I build on the master branch of ASReview pulled just before I wrote the issue.

I didn't change any of the config files.

**Comment by J535D165** [comment]
See also #1569 for more info. Should be resolved now.
