### ISSUE TITLE
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found

### ISSUE THREAD

**Issue by wolfgangmeisen** [asreview/asreview#1598]
**Describe the bug**
Ive installed asreview 3.1.4 in 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview'
The app starts well, but the data folder is not usable, cause default permissions on %Programfiles% (this is part of the secutity concept an cannot change)
Is it possible to separate data folder from app folder via configuration ?  (e.g. on an private share or an local folder) 

see details below
--------------------------------------------------------------------------------------------------------------------------------
:\Windows\system32>asreview lab
Start browser at http://localhost:5000/

If your browser doesn't open. Please navigate to 'http://localhost:5000/'

127.0.0.1 - - [2023-11-29 11:51:32] "GET / HTTP/1.1" 200 713 0.000000
127.0.0.1 - - [2023-11-29 11:51:32] "GET /static/js/main.43c0da44.js HTTP/1.1" 200 1877812 0.143464
127.0.0.1 - - [2023-11-29 11:51:32] "GET /static/css/main.9e747be3.css HTTP/1.1" 200 7690 0.013104
127.0.0.1 - - [2023-11-29 11:51:32] "GET /boot HTTP/1.1" 200 171 0.000998
127.0.0.1 - - [2023-11-29 11:51:32] "GET /boot HTTP/1.1" 200 171 0.000000
127.0.0.1 - - [2023-11-29 11:51:32] "GET /favicon.ico HTTP/1.1" 200 1434 0.000000
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-11-29 11:51:32] "GET /api/projects/stats HTTP/1.1" 404 224 0.009166
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\entry_points' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\io' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\models' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\review' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\state' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\webapp' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\__pycache__' not found
127.0.0.1 - - [2023-11-29 11:51:32] "GET /api/projects HTTP/1.1" 200 122 0.093223
127.0.0.1 - - [2023-11-29 11:51:32] "GET /static/media/asreview_sub_logo_lab_black_transparent.c4e14af313ba97465fff113a6b2e4fd7.svg HTTP/1.1" 200 127815 0.000000
127.0.0.1 - - [2023-11-29 11:51:33] "GET /static/media/roboto-latin-400.176f8f5bd5f02b3abfcf.woff2 HTTP/1.1" 200 16054 0.003057
127.0.0.1 - - [2023-11-29 11:51:33] "GET /static/media/roboto-latin-700.c18ee39fb002ad58b6dc.woff2 HTTP/1.1" 200 16133 0.000000
127.0.0.1 - - [2023-11-29 11:51:33] "GET /static/media/roboto-latin-500.f5b74d7ffcdf85b9dd60.woff2 HTTP/1.1" 200 16189 0.000000
127.0.0.1 - - [2023-11-29 11:51:33] "GET /favicon.ico HTTP/1.1" 304 186 0.000000
127.0.0.1 - - [2023-11-29 11:51:33] "GET /static/media/ElasArrowRightAhead.e624bdd7c691c7c4f6c01604979c8f07.svg HTTP/1.1" 200 14903 0.002997
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-11-29 11:51:33] "GET /api/projects/stats HTTP/1.1" 404 224 0.000000
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-11-29 11:51:35] "GET /api/projects/stats HTTP/1.1" 404 224 0.000000
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-11-29 11:51:39] "GET /api/projects/stats HTTP/1.1" 404 224 0.000000
127.0.0.1 - - [2023-11-29 12:03:47] "POST /api/projects/info HTTP/1.1" 201 345 0.000000
127.0.0.1 - - [2023-11-29 12:03:56] "PUT /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/info HTTP/1.1" 200 355 0.023730
127.0.0.1 - - [2023-11-29 12:04:02] "PUT /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/info HTTP/1.1" 200 359 0.021245
WARNING:root:Expected start tag in line 0:
 The Sysinternals Troubleshooting Utilities have been rolled up into a single Suite of tools. This file contains the individual troubleshooting tools and help files. It does not contain non-troubleshooting tools like the BSOD Screen Saver or NotMyFault.
ERROR:root:Cannot find proper encoding for data file.
127.0.0.1 - - [2023-11-29 12:04:36] "POST /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/data HTTP/1.1" 400 174 0.062180127.0.0.1 - - [2023-11-29 12:04:36] "GET /static/media/roboto-latin-400italic.d022bc70dc1bf7b3425d.woff2 HTTP/1.1" 200 17648 0.001278
127.0.0.1 - - [2023-11-29 12:04:36] "GET /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/info HTTP/1.1" 200 387 0.014989
127.0.0.1 - - [2023-11-29 12:04:36] "GET /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/labeled_stats HTTP/1.1" 200 209 0.000000
127.0.0.1 - - [2023-11-29 12:04:43] "GET /api/datasets?subset=plugin HTTP/1.1" 200 122 0.051071
WARNING:root:Expected start tag in line 0:
 The Sysinternals Troubleshooting Utilities have been rolled up into a single Suite of tools. This file contains the individual troubleshooting tools and help files. It does not contain non-troubleshooting tools like the BSOD Screen Saver or NotMyFault.
ERROR:root:Cannot find proper encoding for data file.
127.0.0.1 - - [2023-11-29 12:04:55] "GET /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/data HTTP/1.1" 400 174 0.022585
WARNING:root:Expected start tag in line 0:
 The Sysinternals Troubleshooting Utilities have been rolled up into a single Suite of tools. This file contains the individual troubleshooting tools and help files. It does not contain non-troubleshooting tools like the BSOD Screen Saver or NotMyFault.
ERROR:root:Cannot find proper encoding for data file.
127.0.0.1 - - [2023-11-29 12:04:56] "GET /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/data HTTP/1.1" 400 174 0.016467
WARNING:root:Expected start tag in line 0:
 The Sysinternals Troubleshooting Utilities have been rolled up into a single Suite of tools. This file contains the individual troubleshooting tools and help files. It does not contain non-troubleshooting tools like the BSOD Screen Saver or NotMyFault.
ERROR:root:Cannot find proper encoding for data file.
127.0.0.1 - - [2023-11-29 12:04:58] "GET /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/data HTTP/1.1" 400 174 0.016586
WARNING:root:Expected start tag in line 0:
 The Sysinternals Troubleshooting Utilities have been rolled up into a single Suite of tools. This file contains the individual troubleshooting tools and help files. It does not contain non-troubleshooting tools like the BSOD Screen Saver or NotMyFault.
ERROR:root:Cannot find proper encoding for data file.
127.0.0.1 - - [2023-11-29 12:05:02] "GET /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/data HTTP/1.1" 400 174 0.016116
127.0.0.1 - - [2023-11-29 12:05:11] "PUT /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/info HTTP/1.1" 200 387 0.009280
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\entry_points' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\io' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\models' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\review' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\state' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\webapp' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\__pycache__' not found
127.0.0.1 - - [2023-11-29 12:05:11] "GET /api/projects HTTP/1.1" 200 400 0.056109
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-11-29 12:05:48] "GET /api/projects/stats HTTP/1.1" 404 224 0.000000
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-11-29 12:05:49] "GET /api/projects/stats HTTP/1.1" 404 224 0.000000
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-11-29 12:05:51] "GET /api/projects/stats HTTP/1.1" 404 224 0.005982
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-11-29 12:05:55] "GET /api/projects/stats HTTP/1.1" 404 224 0.005112
127.0.0.1 - - [2023-11-29 12:06:00] "GET /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/info HTTP/1.1" 200 387 0.003991
127.0.0.1 - - [2023-11-29 12:06:04] "PUT /api/projects/b3bfcfc4fb3641e4af1fae37c470357b/info HTTP/1.1" 200 387 0.007763
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\entry_points' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\io' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\models' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\review' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\state' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\webapp' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\__pycache__' not found
127.0.0.1 - - [2023-11-29 12:06:04] "GET /api/projects HTTP/1.1" 200 400 0.050220

**To Reproduce**
Steps to reproduce the problem:

**Screenshots**

**Version information**
 - OS: Windows 10 22H2
 - ASReview version e.g. 1.3.4

**Additional context**

**Comment by wolfgangmeisen** [comment]
Steps to repruduce the problem:
1.) Destination OS = Windows 10 22H2
2.) Install python in Destination path %programfiles%\python   (Version 3.12)
3.) Install asreview as described. (see my install-doc.) with elevated rights
4.) After successfull Installation Start ASREVIEW with elevated rights
that shows the following log

![image](https://github.com/asreview/asreview/assets/86890250/e638dde1-58d2-4d69-a79e-ff66761f766a)
also as plain text:
---------------------------------------------------------------
Microsoft Windows [Version 10.0.19045.3693]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\system32>asreview lab
Start browser at http://localhost:5000/

If your browser doesn't open. Please navigate to 'http://localhost:5000/'

127.0.0.1 - - [2023-12-14 12:20:54] "GET / HTTP/1.1" 200 713 0.001011
127.0.0.1 - - [2023-12-14 12:20:54] "GET /static/js/main.43c0da44.js HTTP/1.1" 304 194 0.116749
127.0.0.1 - - [2023-12-14 12:20:54] "GET /static/css/main.9e747be3.css HTTP/1.1" 304 192 0.001992
127.0.0.1 - - [2023-12-14 12:20:54] "GET /boot HTTP/1.1" 200 171 0.000000
127.0.0.1 - - [2023-12-14 12:20:54] "GET /boot HTTP/1.1" 200 171 0.000999
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-12-14 12:20:54] "GET /api/projects/stats HTTP/1.1" 404 224 0.015059
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\entry_points' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\io' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\models' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\review' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\state' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\webapp' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\__pycache__' not found
127.0.0.1 - - [2023-12-14 12:20:54] "GET /api/projects HTTP/1.1" 200 400 0.064801
127.0.0.1 - - [2023-12-14 12:20:54] "GET /static/media/asreview_sub_logo_lab_black_transparent.c4e14af313ba97465fff113a6b2e4fd7.svg HTTP/1.1" 304 253 0.009965
127.0.0.1 - - [2023-12-14 12:20:54] "GET /static/media/roboto-latin-500.f5b74d7ffcdf85b9dd60.woff2 HTTP/1.1" 304 218 0.000000
127.0.0.1 - - [2023-12-14 12:20:54] "GET /static/media/roboto-latin-400.176f8f5bd5f02b3abfcf.woff2 HTTP/1.1" 304 219 0.000000
127.0.0.1 - - [2023-12-14 12:20:54] "GET /static/media/roboto-latin-700.c18ee39fb002ad58b6dc.woff2 HTTP/1.1" 304 218 0.001990
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-12-14 12:20:55] "GET /api/projects/stats HTTP/1.1" 404 224 0.000000
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-12-14 12:20:57] "GET /api/projects/stats HTTP/1.1" 404 224 0.000000
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-12-14 12:21:01] "GET /api/projects/stats HTTP/1.1" 404 224 0.005077
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-12-14 12:26:19] "GET /api/projects/stats HTTP/1.1" 404 224 0.000000
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
127.0.0.1 - - [2023-12-14 12:26:23] "GET /api/projects/stats HTTP/1.1" 404 224 0.000000
----------------------------------------------------------------------------------------------------------------------
RESULT:

![image](https://github.com/asreview/asreview/assets/86890250/316e9fe3-94ca-4c8d-bddc-20436c6e2ef6)

**Comment by wolfgangmeisen** [comment]
Add to my last Comment:
For me, it will be the best, to move the data folder to %Programdata%\asrwview. 
Would it be a solution and if Yes, what are the Doings to solve it ?

**Comment by wolfgangmeisen** [comment]
Add to my last C.
as You can see, the folders are in place
![image](https://github.com/asreview/asreview/assets/86890250/fa694e54-24b3-4d3e-8a82-48d454355364)

**Comment by jteijema** [comment]
Hi @wolfgangmeisen, I think we can solve this by moving the entire installation to another location. We can achieve this by putting python and ASReview inside a [virtual environment](https://docs.python.org/3/library/venv.html).

Using the following steps, I installed asreview inside my downloads folder:

```powershell
PS C:\Users\Jelle\Downloads\temp> python -m venv env
PS C:\Users\Jelle\Downloads\temp> .\env\Scripts\activate
(env) PS C:\Users\Jelle\Downloads\temp> pip install asreview
```

I can now run asreview as normal (`>asreview lab`), but if I'm feeling fancy, I could also directly use the asreview executable in our new environment.

```powershell
(env) PS C:\Users\5927226\Downloads\temp> asreview lab
```

```powershell
(env) PS C:\Users\5927226\Downloads\temp> .\env\Scripts\asreview.exe lab
```

I realise this is not a very convenient option and more of a work-around, but if you have no administrator rights of the program files directory, then this might be the solution. Another option would be installing python to another location.

**Comment by wolfgangmeisen** [comment]
Thank You, jteijema for Your Answer.

let me explain, why we can't Do this way.

python and asreview will install automaticly (aut Deployment) in an windows environmat.
Windows split strickly code, (%program% configuration %ProgramData% and user- data (e.g. %Homeshare%)  in seperate folders. This folders have several permissions, That is neccesary to commit the common security Requirements for Endpoints.

As I can mentioned, DIPF and many other Institute are under Firefrom  the hacking Community. So we have to change our mindset up to much more security for any people and the Institut itself.

Your Solution doesnt face this circumstands. So im not able to use it (btw: that was the defautl installation procedure.) 

Is there any other way (e.g.- evironment variable als a pointer on da new data folder in %Homeshare% ?

or: as an secure Server Installation with an Web Interface ?

or .....


regards
Wolfgang

**Comment by wolfgangmeisen** [comment]
i ve studied  the Server-documenton on asreview.readthedocs.io and have some questions. 
Whitch OS will be supportet ? (Version/Release)
Whre is the ASreview Installation document for server use.
How can i check the Installation.?
I semms to be, that the server install need more supprt that the client installation. Cause of our small it-team, i think it is more sense to use the client installation.

Is there no way to split the data from the code / configuration on the client ?

**Comment by jteijema** [comment]
I doubt actually only the data folder is the issue:

```
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\data' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\entry_points' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\io' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\models' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\review' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\state' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview\webapp' not found
ERROR:root:Project 'C:\Program Files\Python\Python3.12\Lib\site-packages\asreview_pycache_' not found
```

This suggests to me a lot of folders have this permission issue, not only the data folder.

**Comment by wolfgangmeisen** [comment]
Sure, there are more than the data Folder. the other once are Code & configuration folder without user interaction (hopefully). I guess it is possible to elevate the permission without security leaks, but i ve to check it in the next few days.
