### ISSUE TITLE
Port specification in .env file

### ISSUE THREAD

**Issue by beffersr** [asreview/asreview#1605]
We try to install ASReview on a server using the dockerfile, which seems to work fine. Because the default ports that are used are already in use, we have to specify new ports. We do so in the .env file:
BACKEND_EXTERNAL_PORT=5015 -> 5003
BACKEND_INTERNAL_PORT=5005

EMAIL_PASSWORD="password"
WORKERS=4

FRONTEND_EXTERNAL_PORT=8080 -> 5002
FRONTEND_INTERNAL_PORT=80

POSTGRES_EXTERNAL_PORT=5433 -> 5004
POSTGRES_INTERNAL_PORT=5432

POSTGRES_PASSWORD="postgres"
POSTGRES_USER="postgres"
POSTGRES_DB="asreview_db"

The following error occurs:
![image](https://github.com/asreview/asreview/assets/2564749/47ad5cb9-dadd-41fe-852f-010f3369685e)

**Version information**
 - OS: Linux
 - ASReview version: latest

**Comment by J535D165** [comment]
Thanks @beffersr for reporting. @cskaandorp can I assign you to this?

**Comment by cskaandorp** [comment]
> Thanks @beffersr for reporting. @cskaandorp can I assign you to this?

Noted, I will look into this asap. If not this week, than on Monday.

**Comment by cskaandorp** [comment]
I have found an issue, but it's about not using port 8080 for the frontend. I can not reproduce the error in the image. Will try to contact @beffersr

**Comment by J535D165** [comment]
Most likely fixed in #1607. Thanks for reporting.
