### ISSUE TITLE
When naming the title of a new project, it says "Error, no response received"

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#1684]
### Discussed in https://github.com/asreview/asreview/discussions/1683

<div type='discussions-op-text'>

<sup>Originally posted by **bueredlemon11** February  8, 2024</sup>
Hello guys,
I'm new to ASReview, when I tried to create a new project, in the field "Title(required)", no matter what title I put, it always shows "Error, no response received". So I'm stuck at the first step...
Does anyone know why? Thanks in advance！

![Title error1](https://github.com/asreview/asreview/assets/131249758/9357cb6f-76ba-4b7d-a2a1-e77c0d7d139d)

</div>

**Comment by Joanna40433322** [comment]
Do you know how to solve this problem, I also encountered this problem, thank you very much！

**Comment by CharlieWolve** [comment]
Did you perhaps close Command Prompt? I also ran into this problem, but at a later step and I realized I had closed Command Prompt shortly before that. Because it said website not available after reloading, I restarted it and left Command Prompt open this time. Now it worked
