### ISSUE TITLE
Updating ASReview to Python 3.12

### ISSUE THREAD

**Issue by taleevenhuis** [asreview/asreview#1689]
In December, last year, I found out that not all the models were working fine, especially Sentence BERT in combination with fully connected CNN. My Python Version was at that moment 3.12. 

One of the ASReview-members noticed that this model works best with Python 3.11. When he succeeded to reinstall Python 3.11, Sentence BERT in combination with fully connected CNN, worked smoothly again.
One of the researchers I'm helping to work with ASReview, noticed the same trouble SBERT and CNN and his Python version is also 3.12.

Is it possible to update ASReview, that SBERT and CNN also works at Python 3.12?

**Comment by jteijema** [comment]
Hi @taleevenhuis 

The issue with python 3.12 lies not with ASReview itself, but with one of the packages ASReview uses. Tensorflow, Keras and transformers all have their separate issues with this. I can only assume the developers of those packages are working on new versions, but this is sadly not something we can solve! This is why we promote 3.8 as a standard. 

Often newer versions of software have better performance, therefore it's understandable to want to use the latest version, however this is not exactly the case with python. Python adds new features, but as long as those features aren't used, I daresay there is nothing to be gained by using 3.12 :)

P.S., the CNN model has moved to a different package, https://github.com/jteijema/ASReview-experimental-models

^JT

**Comment by J535D165** [comment]
Tensorflow now supports Python 3.12. Everything should work as expected again.

**Comment by taleevenhuis** [comment]
I'm very sorry Jonathan. Last week, a researcher from the Hogeschool Utrecht, still had a problem working with the combination SBERT en Neural Network. See the added picture!
![Error SBERT-NN](https://github.com/asreview/asreview/assets/132048494/fe812005-f2aa-4b97-b0e1-1bbd3b774b51)

The researcher works with Python 3.12.
