### ISSUE TITLE
Project not visible in homepage after laptop restart

### ISSUE THREAD

**Issue by JDean934** [asreview/asreview#1691]
Hello!

Yesterday my laptop automatically updated while I had a project open in ASReview. Today I opened ASReview and this project does not show up in the menu anymore. I can still see previous projects listed, and the project folder is still present in the .asreview folder.

This is what I see:
![image](https://github.com/asreview/asreview/assets/160595488/d658c909-3a3d-48c3-868c-f298f1a69363)
 
![image](https://github.com/asreview/asreview/assets/160595488/dee58f28-6376-4a95-9828-c4cd8736f7ad)

**Version information**
- OS: Windows
- ASReview version: latest version

I was wondering if anyone has suggestions for how to get the project back?

**Comment by J535D165** [comment]
Sorry for the inconvenience. This is the first time I have seen this, but I suspect something went wrong while writing one of the JSON files in the folder. There are 2 JSON files in the project folder: `project.json` and `settings_metadata.json` (in the reviews folder). Can you open these files? Is there content?

**Comment by J535D165** [comment]
Feel also free to zip this project folder and send it to asreview@uu.nl

**Comment by JDean934** [comment]
The file project.json was empty. I copied it from another project and filled in the details of the current project; this fixed the problem. Thanks so much for the help!
