### ISSUE TITLE
n_jobs for logisticRegression is not usable

### ISSUE THREAD

**Issue by strayMat** [asreview/asreview#1740]
**Description of the issue :  **
We are proposing a `n_jobs` parameter for the [asreview.models.classifiers.logistic  classifier](https://github.com/asreview/asreview/blob/main/asreview/models/classifiers/logistic.py#L51) . This parameter is passed to the underlying [sklearn.linear_model LogisticRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression). However this classifier makes use of n_jobs>1 only in case of multi class classification (and with another solver than liblinear that is used as default in asreview). Because we are only facing a binary classification task in ASReview, this `n_jobs` parameter seems not needed.  

**Changes needed**:  
I would suggest to remove the `n_jobs` parameter from the asreview logistic classifier because changing it does not change anything to the learning pipeline. I will be happy to implement a PR if this is pertinent. 

NB: I am not aware that we are doing some HP selection on top of the ASreview logistic classifier. However, if this is the case, we should keep n_jobs=-1 for the asreview.logistic classfiier to pass it to HP selection but we can still remove it from the sklearn.linear_model Logistic regression.

**Comment by J535D165** [comment]
I like the idea. PR is welcome!

**Comment by strayMat** [comment]
PR provided here :)  https://github.com/asreview/asreview/pull/1742
