### ISSUE TITLE
Progress information

### ISSUE THREAD

**Issue by marko-ogorevc** [asreview/asreview#1745]
Please add progress information in some way on or next to the circle, that's probably displaying circular progress bar. Having information in %completed or ETA would make it more intuitive.

**Comment by laurens88** [comment]
In the analytics tab there is such a circular graph (blue circle represents screening progress) but currently it includes the training priors. Would be nice to be able to toggle priors on and off. On desktop you can hover over the blue circle to see the progress as percentage and you can click on it on the mobile version but it would be more useful to have it as default value in the chart!
![image](https://github.com/asreview/asreview/assets/96109694/69dda290-0484-4fbf-a2d8-fdc0992db30b)

**Comment by J535D165** [comment]
We resolved this issue, and it will be included in the next release. cc @BerkeYazan
