### ISSUE TITLE
project information

### ISSUE THREAD

**Issue by ronewam24** [asreview/asreview#1753]
**Describe the bug**
_What happened? And what did you expect to happen?_
on project information, when i enter the tittle and proceed to the next step of data it immediately takes me back to project information and reports "error, no response recieved" on my title
**To Reproduce**
Steps to reproduce the problem:

**Screenshots**

**Version information**

- OS: [e.g. Windows]
- ASReview version [e.g. 0.6.2]

**Additional context**

**Comment by Rensvandeschoot** [comment]
What is the message you receive in the CLI?
