### ISSUE TITLE
Export dataset error - maximum recursion depth

### ISSUE THREAD

**Issue by kathng23** [asreview/asreview#1755]
I tried to export the data in either cvs or excel file, but got an error message
"Failed to export the csv dataset. maximum recursion depth exceeded while calling a Python object Please try again."
"Failed to export the xlsx dataset. maximum recursion depth exceeded while calling a Python object Please try again."

![Screenshot 2024-05-30 173303](https://github.com/asreview/asreview/assets/116720467/ea78227d-2465-494c-9222-a3ab17013669)

**Version information**
- OS: Windows 10.0.22631
- ASReview version: 1.6.2

**Comment by J535D165** [comment]
Thanks for reporting, @kathng23. Can you send your project (export it from the same screen as Project) to asreview@uu.nl? I will look into it.

**Comment by J535D165** [comment]
@jteijema 

https://github.com/asreview/asreview/blob/1.6.x/asreview/webapp/api/projects.py#L1153-L1231

This error is poorly designed therefore we can't see what is happening. Should be "raise Exception() from err"
https://github.com/asreview/asreview/blob/f6774b74d6eec1fd402e760b1c9786af1a4d39ee/asreview/webapp/api/projects.py#L1232-L1233
