### ISSUE TITLE
Unable to run Doc2Vec

### ISSUE THREAD

**Issue by kathng23** [asreview/asreview#1757]
I wanted to use the Doc2Vec technique for my extraction, have installed gensim package and all dependency with pip install asreview[all], but when I ran it, it kept returning: ImportError: Install gensim package to use Doc2Vec 

![Screenshot 2024-06-03 144506](https://github.com/asreview/asreview/assets/116720467/47ba7263-7ff9-4dd9-8625-12435fde14fd)

- OS: Windows 10.0.22631
- ASReview version: 1.6.2
- Python 3.11.9

I tried clean installing both python and ASReview on a different device, and the problem also occurred

**Comment by Rensvandeschoot** [comment]
Could you try 
```
pip install asreview[gensim]
```

**Comment by kathng23** [comment]
Hi @Rensvandeschoot, I also did that, and it didn't work still

**Comment by TimothyMarcroft** [comment]
Just jumping in to say say problem and same basic system config: Windows 10 with a fresh install of Python 3.11.9 & a fresh install of Asreview. I actually did this fresh install of a downgraded Python so that I could try out sBERT, which works fine, but I wanted to also test doc2vec as I prefer a naive model.

**Comment by kathng23** [comment]
@TimothyMarcroft hey so I think I kinda figured out what the problem was and the solution for it. So basically SciPy is needed to run gensim, but the newest update of scipy does not support gensim. I just down graded scipy with

`pip install scipy==1.11.0`

See [piskvorky/gensim#3525](https://github.com/piskvorky/gensim/issues/3525) for a more detailed explanation.

**Comment by TimothyMarcroft** [comment]
@kathng23 Hey! Thanks so much for coming back with that answer! I did as you suggested and it seems to be working (AI is warming up now with my 3500+ previous knowledge records). Thank goodness for smart and helpful people like you.

**Comment by brelsford** [comment]
I've got a related issue:  I'd like to run ASReview with sBERT, but I can't get my installation to recognize any of the optional dependencies.  I've tried on two machines (work machine, with complicated security stuff, MacOS Ventura) and also a personal machine:

*macOS 14.6.1
*python 3.11.10 (started with 3.12)
*asreview 1.6.2 
*scipy 1.11 (also tried 1.13)

*this is a new installation of python, and I've deleted and recreated the basic env several times hoping something works, following the package suggestions in here, [this thread](https://github.com/asreview/asreview/issues/1799), and [this thread](https://github.com/asreview/asreview/issues/1689)
*in my asreview installation, I install all optional dependencies, but none are recognized:  asreview complains about gensim when I try doc2vec embedding, sentence-transformers for SBERT, and tensorflow  for Embedding IDF.

**Comment by timovdk** [comment]
Hi @brelsford! Thank you for your detailed description of the issue you're encountering. We were able to reproduce your problem, and are currently working on a potential fix. We will keep you posted in this thread!

**Comment by brelsford** [comment]
Hi Folks (@timovdk): my current workaround is to use a different operating system.  
I can run sBERT without error on 
*Ubuntu 24.04.1 LTS
*python 3.11
*asreview 1.6.3
*scipy 1.13.1

which are just the defaults in a clean 3.11 environment after `pip install asreview[all]`

**Comment by timovdk** [comment]
Hi @brelsford,
Thanks for getting back to us! I'm very happy it's working for you right now!
