### ISSUE TITLE
ASReview won't open after installing pip asreview[all], [WinError 126] error specified module cannot be found 

### ISSUE THREAD

**Issue by TessadeBie** [asreview/asreview#1799]
I'm in phase 3 of the SAFE procedure, and want to use the SBERT module with the neural network 2 layer. 
After installing pip asreview[all] I got the following error when I want to open ASReview lab: 

![2024-08-01T10_09_14](https://github.com/user-attachments/assets/a700c9af-9502-4836-917e-2496305b3ffe)

ASReview wont open. 
With PIP freeze I noticed that torch is succesfully installed. 
So I don't understand what is going wrong.

![2024-08-01T10_15_15](https://github.com/user-attachments/assets/c72356f4-491f-4d93-9079-cde649e850f0)

anyone that has the same problem or has the answer to fix this? 

**Version information**

- OS: windows
- Browser edge
- ASReview version 1.6.2

**Comment by TessadeBie** [comment]
after removing torch, ASReview opens, but SBERT won't run since torch is requiered to run SBERT.

**Comment by jteijema** [comment]
This seems to be a problem with pytorch, here's a recent thread:

https://github.com/pytorch/pytorch/issues/131662

Some potential solutions have been offered in the thread, maybe one of those will work. 

!pip uninstall torch
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

**Comment by TessadeBie** [comment]
Thank you,
We solved it with the following:
pip install scipy==1.14.0
pip install torch==2.3.1
pip install tf-keras 

it seems to be working again. ASReview opens and SBERT is loading without giving an error.

**Comment by jteijema** [comment]
Perfect! Closing thread. Thanks for posting the solution.
