### ISSUE TITLE
Asreview can not open after installing pip asreview[all] and reinstalling Python 3.12.5

### ISSUE THREAD

**Issue by zaq0718** [asreview/asreview#1809]
**Describe the bug**
Hello, after installing pip asreview[all], I received [WinError 126] error. Then, I re-installed Python 3.12.5 . However, I can not open asreview (code: asreview lab). As the messages are quite long, i attached the copy of the message.
-- asreview lab (this showed that:  2024-08-21 07:33:24.044183: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.)

[Intalling Asreview_errors_docx.docx](https://github.com/user-attachments/files/16686522/Intalling.Asreview_errors_docx.docx)

**To Reproduce**
Steps to reproduce the problem:

**Screenshots**

**Version information**

- OS: [Windows 10]
- Browser [Chrome]
- Python version [3.12.5]

**Comment by zaq0718** [comment]
I found solutions to solve this issue. The soultions are two steps.
Step 1: Given the message: If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2
I installed "numpy <2" based on the following code 
`pip install "numpy<2`
Related reference: https://github.com/DeepLabCut/DeepLabCut/issues/2624

Step 2: However, I still received an error message: Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback): Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.

Then, I installed "tf-keras" `pip install tf-keras`.

In the end, it worked. Hope this solution is helpful for others.

**Comment by jteijema** [comment]
Thank you @zaq0718 , this helped me out today!
