### ISSUE TITLE
Documentation on Active Learning and Systematic reviewing.

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#183]
It would be nice to have a (more) scientific tutorial on the techniques and methods used in this project. Think about topics like:

On active learning: 

- [x] Active learning (A short introduction in Active Learning, 20 lines?)
- [ ] Query strategies (A short introduction in query strategies, 20 lines?)
- [ ] Human AI interaction
- [x] Word Embeddings

Contribute to https://github.com/asreview/asreview/blob/master/docs/source/activelearning.rst

On Systematic Reviewing:

- [ ] What is systematic reviewing?
- [ ] PRISMA 

Contribute to https://github.com/asreview/asreview/blob/master/docs/source/sysrev.rst

Or drop your narrative in the comments below. 

Your contribution will become part of our new tutorial on ASReview (for the new user interface)

@GerbrichFerdinands @qubixes

**Comment by Sasafrass** [comment]
Hi,

I can write a piece on active learning if you want? When do you need it?

**Comment by J535D165** [comment]
Would be great! Would be nice to have some draft this weekend :)

**Comment by GerbrichFerdinands** [comment]
I added a piece on word embeddings, checkout my pr [here](https://github.com/asreview/asreview/pull/185 )
