### ISSUE TITLE
Python3.8 reached end-of-life

### ISSUE THREAD

**Issue by PeterLombaers** [asreview/asreview#1883]
Python3.8 reached it's end-of-life (see https://devguide.python.org/versions/). This means that no more updates are made to it, not even security updates. I think we should require at least Python3.9 for ASReview v2. Maybe we should even require a higher version of Python if we want to make use of modern typing features?

**Comment by J535D165** [comment]
Bumping to 3.10 for V2 makes sense to me. It also resolves the importlib_metadata backport.

Will work on it.
