### ISSUE TITLE
Standardize docstrings

### ISSUE THREAD

**Issue by PeterLombaers** [asreview/asreview#1911]
In function docstrings, for the section describing the input arguments, we use both `Arguments` and `Parameters`. I think `Arguments` is more common, but `Parameters` occurs a couple of times. We should pick one so that automatically generating documentation is easier.

**Comment by J535D165** [comment]
According to the sphinx config file (`conf.py`), we try to parse Numpy docstrings https://numpydoc.readthedocs.io/en/latest/format.html#parameters. It prefers "Parameters". Shall we implement Numpy docstrings a bit stricter and replace Arguments by Parameters?
