### ISSUE TITLE
I can't install Sklearn to use ASREVIEW extensions

### ISSUE THREAD

**Issue by JoaoVictorNH** [asreview/asreview#1980]
I'm trying to install an extension, but when I run the installation and it searches for the sklearn library, an error occurs that interrupts the process.

**To Reproduce**
Steps to reproduce the problem:

1) Access the terminal and run the installation command:
`pip install git+https://github.com/asreview/asreview-multilingual-feature-extractor.git`

![image](https://github.com/user-attachments/assets/e0b7fe30-ebbb-4a2c-b8b4-3221b3253c99)

2) Execution result:

`PS C:\WINDOWS\system32> pip install git+https://github.com/asreview/asreview-multilingual-feature-extractor.git
Collecting git+https://github.com/asreview/asreview-multilingual-feature-extractor.git
  Cloning https://github.com/asreview/asreview-multilingual-feature-extractor.git to c:\users\joaov\appdata\local\temp\pip-req-build-zli54kuk
  Running command git clone --filter=blob:none --quiet https://github.com/asreview/asreview-multilingual-feature-extractor.git 'C:\Users\joaov\AppData\Local\Temp\pip-req-build-zli54kuk'
  Resolved https://github.com/asreview/asreview-multilingual-feature-extractor.git to commit 0a017c02c8ca8bf262bd0616007a57f7c51f8e09
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sklearn (from asreview-multilingual-feature-extractor==0.1)
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\WINDOWS\system32>`

![image](https://github.com/user-attachments/assets/1d1c7fc3-b40e-47e4-91ef-6f38f3d5f4a3)

**Version information**

- OS: Windows 11
- Browser: Edge
- ASReview version: 1.63

**Additional context**

I need the sklearn package to perform some functions such as using CNN.

**Comment by timovdk** [comment]
Hi @JoaoVictorNH,
Thank you for the elaborate explanation. This is an issue with the [asreview multilingual feature extractor](https://github.com/asreview/asreview-multilingual-feature-extractor), not asreview itself.
@J535D165 could you move this issue to the linked repo?

**Comment by timovdk** [comment]
Hi @JoaoVictorNH, This issue was fixed in the linked repository, [PR](https://github.com/asreview/asreview-multilingual-feature-extractor/pull/4#issue-2741884671) I will close this issue.
