### ISSUE TITLE
Remaining training time

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview#202]
it would be nice to also show estimated remaining training time for the first iteration

**Comment by Sybren-UU** [comment]
I think you'r talking about step five in ASReview, maybe it would be nice to have a picture of Elas with a think ballon with a loading animation.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/60712710/80195250-d68c9d80-861b-11ea-8f48-221e40f18f6a.png">

**Comment by J535D165** [comment]
It's complicated/impossible to estimate the time remaining. In #312, we implement a training animation (spinner).
