### ISSUE TITLE
Percentage in statistics panel

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview#204]
For the statistics panel, I think it would be nice to also show the number in percentage (e.g. percentage of relevant among all articles). To help users decide on when to stop, it might be a good idea to also show the number of articles marked as irrelevant continuously (i.e. the last X presented abstracts were labelled irrelevant). Would be nice to show it as a percentage too.

**Comment by J535D165** [comment]
Closed in #214
