### ISSUE TITLE
Broken CI pipeline

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#217]
After commit https://github.com/asreview/asreview/commit/69aa823283ee88938787035bd60f837a778ac315 by @Rensvandeschoot, our CI pipeline broke. This commit contains documentation only, while the pipeline fails on compiling the Javascript code. 

It might be a change to Github Actions. This will fail our build and deploy pipeline as well (I guess). 

``` bash

Creating an optimized production build...

Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

``` 

@qubixes, do you have time to have a look?

**Comment by qubixes** [comment]
@J535D165 Ehm, I'm not sure what you want me to do. Maybe it's the easiest/best to fix the warnings? I'm sure other people/you know better how to fix javascript dependencies than me...

**Comment by J535D165** [comment]
Resolved
