### ISSUE TITLE
Add RIS export

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#225]
RIS export is very useful for users because of the integration with reference managers. 

Open questions:

- The field and/or format of the field containing the label
- Single file export or multi-file export

**Comment by GerbrichFerdinands** [comment]
After some discussion, we decided we should go for multi-file export, e.g. a file with all included articles, a file with all excluded articles, and a file with all unlabeled articles. The user can then easily import these files in a reference manager. 

As this feature is currently not available yet, I found a workaround in the R-package `bib2df`. 
This package is able to transform `.bib` files to tabular data (a format suitable for ASReview), and vice versa. 

I tried it out, and with this script I was able to convert the ASReview `.csv` export to three `.bib` files.


```
# load packages
library(bib2df)
library(readr)
library(tidyverse)

# load ASReview export (that was once transformed from bib to csv by bib2df)
asreview_export_file <- "~/Downloads/asreview_result_my-systematic-review.csv"
asreview_result <- read_csv(asreivew_export_file) %>%
  rename(Bibtexkey = bibtexkey,
         AUTHOR = author,
         Category = category)

# split up in 3 datasets
relevant <- asreview_result %>% filter(label == 1)
irrelevant <- asreview_result %>% filter(label == 0)
unlabeled <- asreview_result %>% filter(is.na(label))

# write to bib files 
df2bib(relevant, "~/Downloads/relevant.bib")
df2bib(irrelevant, "~/Downloads/irrelevant.bib")
df2bib(unlabeled, "~/Downloads/unlabeled.bib")
```

Now you can open these datasets with your reference manager, for example in Zotero.
In Zotero, a record from this file looks like this: 

<img width="336" alt="image" src="https://user-images.githubusercontent.com/45358236/101180125-777c1600-364b-11eb-8181-8b92090ccc2b.png">

This simple script works quite well, however, I've identified a couple of problems: 
- Some parsing problems with column names, see the `rename` function I had to use
- There is a problem with parsing multiple authors (they show up in one author field). This is probably quite easy to fix by transforming the authors into a list.
- I wasn't able to import these files into endnote yet, but with some import filter, I think this should be possible. 

I invite anyone interested to test and improve this script. More info on the correct format can be found [here](http://127.0.0.1:24350/library/bib2df/doc/bib2df.html). 
Also, help with testing the output files in other reference managers is more than welcome!

**Comment by Rensvandeschoot** [comment]
Thanks @GerbrichFerdinands !!! This will be very helpful for many researchers until we have a ris-export option available

**Comment by paprika27** [comment]
I have written this to help me export selected rows from the xlsx(m) result export of version .15 to bibtex:

    Sub Write_bib()
    Dim strFile_Path As String
    strFile_Path = ThisWorkbook.Path & "\export.bib"
    Open strFile_Path For Append As #1
    
    Dim a As Range, r As Range, y As Long
    
    Set a = Selection
    
    For Each r In a.Rows
        y = r.Row
        Print #1, "@article{" & Cells(y, 1).Value & ","
        Print #1, "title={" & Cells(y, 23).Value & "},"
        Print #1, "author={" & Cells(y, 5).Value & "},"
        Print #1, "journal={" & Cells(y, 10).Value & "},"
        Print #1, "volume={" & Cells(y, 24).Value & "},"
        Print #1, "number={" & Cells(y, 25).Value & "},"
        Print #1, "pages={" & Cells(y, 21).Value & "},"
        Print #1, "year={" & Cells(y, 9).Value & "},"
        Print #1, "abstract={" & Cells(y, 3).Value & "},"
        Print #1, "doi={" & Cells(y, 27).Value & "}"
        Print #1, "}"
        Print #1, ""
    Next
    
    Close #1

    End Sub

**Comment by Rensvandeschoot** [comment]
we continue the discussion in https://github.com/asreview/asreview/issues/495
