### ISSUE TITLE
User gets stuck in Start Reviewing (step 5)

### ISSUE THREAD

**Issue by LeonTQS** [asreview/asreview#234]
When the user arrives in step 5 - Start Reviewing the button Start Review needs to be clicked. Next, the text 'Training model... (this can take some time)' is displayed. Currently no papers are displayed (waited for 10 minutes), the user appears to be stuck.

However, when you go the Projects and select the project (above), you arrive in step 5 right away and the 1st paper is presented.

**Comment by J535D165** [comment]
Thanks! Might relate to #206

**Comment by qubixes** [comment]
@LeonTQS Which version of ASReview is used, any training options that were selected?

**Comment by LeonTQS** [comment]
version 0.8.9 with dataset PTSD_VandeSchoot. Haven't tested explicitely but is seems to appear with every dataset already present (5).

**Comment by LeonTQS** [comment]
@qubixes see comment above

**Comment by qubixes** [comment]
@LeonTQS Is there any output in the terminal?

**Comment by LeonTQS** [comment]
<img width="942" alt="File not found" src="https://user-images.githubusercontent.com/63716760/79332314-ea9a1600-7f1c-11ea-8394-17cfa22e52f4.PNG">
@qubixes

**Comment by qubixes** [comment]
Hmmm, that's strange. Is the file anywhere in the base folder at all? Any other suspicious messages?

**Comment by LeonTQS** [comment]
@qubixes it doesn't seem to be but I might be looking at the wrong place...

2 observations though, I do get the message 'succesfully included' in step 3, and when I open the project from the Projects tab, step 5 is displayed including publications (and I can continue reviewing).

**Comment by LeonTQS** [comment]
@qubixes this is not happening anymore in the new release, tested with all 4 new options in step 5.
Closed the bug.

**Comment by J535D165** [comment]
Thanks for testing. Closed in #254
