### ISSUE TITLE
Wrong location for Export option 

### ISSUE THREAD

**Issue by LeonTQS** [asreview/asreview#235]
The Export option is currently placed in the main menu on the left side. All options in this menu are 'generic' expect for the Export option which is project specific. 

Therefore it would make much more sense in my opinion to locate this option in step 5 in the Statistics tab on the right side (prob should be open by default as well).

**Comment by J535D165** [comment]
Agree

Todo:

- [ ] Statistics panel open by default
- [ ] Export button to the right-hand side
