### ISSUE TITLE
Location of Add project icon (red circle) is fixed

### ISSUE THREAD

**Issue by LeonTQS** [asreview/asreview#246]
The location of Add project icon (red circle) is fixed at the bottom right corner of the Project tab. Not an issue when the user has not too many projects, but with many, the location of the button becomes weird (e.g. halfway on the Projects page).
<img width="929" alt="Location Add Project button is fixed" src="https://user-images.githubusercontent.com/63716760/79571576-af821900-80bb-11ea-8269-f848b3abf2ec.PNG">

**Comment by J535D165** [comment]
You look like a dedicated researcher with a lot of ongoing projects ;) 

Thanks for reporting. I will resolve it.
