### ISSUE TITLE
"New" button is not working when one is already working in a project. 

### ISSUE THREAD

**Issue by GerbrichFerdinands** [asreview/asreview#253]
**Describe the bug**
The menu on the left offers the option to create a new project through the `New` button. This button opens a new project when I am on the Projects page, but does not do anything when I am already in a  project. 

**To Reproduce**
Steps to reproduce the problem:

I made a mistake in selecting inclusions so I wanted to quit the current project and start a new one by clicking the `New` button. 

**Version information**
 - OS: macOS 10.15.2
 - ASReview version: 0.9rc1

**Comment by J535D165** [comment]
Thanks @GerbrichFerdinands. I can reproduce this. This only happens in the pre-review step. I will have a look.
