### ISSUE TITLE
Only blank entries after succesfully opening CSV

### ISSUE THREAD

**Issue by maartenhoog** [asreview/asreview#255]
**Describe the bug**
When I run 0.9rc2, and successfully import a csv, then the rest of the worklow shows only blank titles+abstracts.

**To Reproduce**
Steps to reproduce the problem:

* I installed latest version by downloading whl: Successfully installed asreview-0.9rc2
* Run asreview in oracle mode
* exported a dataset from a search query from https://www-computer-org.proxy.library.uu.nl/csdl/search/default?type=basic&basicSearchText=%22virtual%20research%20environment%22%20OR%20%22VRE%22
* created new project, drag exported file into the project
* When searching for records to include, only blank titles are shown
* etc.

**Screenshots**
![Screen Shot 2020-04-19 at 12 16 36](https://user-images.githubusercontent.com/11409952/79685262-bdf53f80-8237-11ea-84f1-ea399236f162.png)

![Screen Shot 2020-04-19 at 11 55 51](https://user-images.githubusercontent.com/11409952/79685034-f431bf80-8235-11ea-9d65-39878a5ab730.png)
![Screen Shot 2020-04-19 at 11 56 04](https://user-images.githubusercontent.com/11409952/79685036-f562ec80-8235-11ea-9487-53938bc879a3.png)
![Screen Shot 2020-04-19 at 11 56 23](https://user-images.githubusercontent.com/11409952/79685040-f7c54680-8235-11ea-8081-c63ba200fb1a.png)
![Screen Shot 2020-04-19 at 11 56 28](https://user-images.githubusercontent.com/11409952/79685045-fc89fa80-8235-11ea-8845-3cda95161de4.png)
![Screen Shot 2020-04-19 at 11 56 50](https://user-images.githubusercontent.com/11409952/79685050-001d8180-8236-11ea-9ba3-014312cbb08d.png)

**Version information**
 - OS: MacOS 10.13.6
 - ASReview version 0.9rc2

**Additional context**

**Comment by Rensvandeschoot** [comment]
Thanks for letting us know! We'll come back to you as soon as we found a solution!

**Comment by J535D165** [comment]
Thanks @maartenhoog. Export is with title case for column labels like title and abstract.  This is accepted on file validation in ASReview, but is seems not possible to retrieve later on. This is a bug.

@qubixes Can you fix this and write a unit test.

```
"Title","Authors","Affiliations","Abstract","Publication","Category","DOI"
"A Virtual Research Environment (VRE) for Bioscience Researchers","Savas Parastatidis, Roger S. Barga, Stephen Andrews",,"In this paper we present the Research Information Centre (RIC), a virtual research environment being jointly developed by the Technical Computing Group at Microsoft and The British Library. We view researchers as extreme information workers and the purpose of the RIC is to support researchers in managing the increasingly complex range of tasks involved in carrying out research. Our first implementation of the RIC is focused on the biomedical researcher, leveraging commercial off-the-shelf software to the extent possible. However, the base architecture of RIC is designed so that it can be re-used for research in other domains.","Advanced Engineering Computing and Applications in Sciences, International Conference on","Conference Publication","10.1109/ADVCOMP.2007.14"
"Towards Grid Services for a Virtual Research Environment","Simon Grange, Les A. Carr, Gary B. Wills, Lester Gilbert, Wendy Hall, Hugh C. Davis, Quintin Gee, David E. Millard, Tim Miles-Board",,"VOEU is a virtual university which we designed,  implemented and deployed in the Wessex Region of the  UK for use by Higher Surgical Trainees in the  Orthopaedic domain. A particularly original part of  this virtual university is the Virtual Research  Environment (VRE) which provides the infrastructure  to support trainee surgeons in carrying out and  publishing research and clinical trails. The current  implementation of the VRE is tightly coupled, but we  are now engaged in a new project to redeploy the VRE  as loosely coupled grid services. This paper describes  the VRE, and discusses the advantages that will be  achieved by implementing it as grid services.","Proceedings. 5th IEEE International Conference on Advanced Learning Technologies","Conference Publication","10.1109/ICALT.2005.290"
```

**Comment by J535D165** [comment]
@maartenhoog It now works. Thanks for reporting and we are working on unit tests

![localhost_3000_(iPad) (2)](https://user-images.githubusercontent.com/12981139/79697543-ae9be380-8283-11ea-9cb4-ce88c53a6bad.png)
