### ISSUE TITLE
End-user testing | relevant articles are not displayed in red 

### ISSUE THREAD

**Issue by GerbrichFerdinands** [asreview/asreview#270]
**Describe the bug**
I was running a test review with the built-in example PTSD dataset. Upon screening, I expect the relevant publications to be shown in red, and the irrelevant publications in black. However, all publications are displayed in black text, regardless their relevancy. 

**To Reproduce**
Follow the steps from the [end-user testing guide](https://asreview.readthedocs.io/en/latest/user_testing_algorithms.html). In other words: create a project with one of the example datasets, and start screening. 

**Screenshots**
For example, this publication is relevant, but the text colour is black. 
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/45358236/84177438-2962cd00-aa83-11ea-8e0f-b055badd419f.png">

**Version information**
 - OS: macOS (15)
 - ASReview version 0.9.5
 - Browser: Chrome

**Comment by J535D165** [comment]
Can anyone test this with the previous versions of ASReview? Which version introduces this bug?
