### ISSUE TITLE
Allow to run ASReview directly as docker image

### ISSUE THREAD

**Issue by behrica** [asreview/asreview#274]
## Feature Request
To have a "ready-made" Docker image on Dockerhub would be the shortest path to try the software.

 I could help with that, but probbaly the docker image should be under "your account" on dockerhub.

I could contribute a Dockerfile including usage instructions and upload it to "my"  docker hub account, if that helps.

**Comment by behrica** [comment]
I went a bit ahead and uploaded asreview to my Docker account.

Si it can be run for everyboddy like this:

```
docker run behrica/asreview
```

**Comment by J535D165** [comment]
Hi @behrica, thanks for reaching out with this very interesting idea. It would be nice to have a PR such that we can work on an official ASReview Docker image. Can you help us with this?

**Comment by behrica** [comment]
Yes,  I will send PR with Dockerfile and instructions.  Maybe you look at registering a docker hub account,  where the Dockerimage would be uploaded

**Comment by behrica** [comment]
is closed
