### ISSUE TITLE
Checks before deleting a project fail

### ISSUE THREAD

**Issue by terrymyc** [asreview/asreview#291]
In the project settings, you should delete a project by typing the project name. Although the delete button is disabled:
- If you don't type, you can still delete a project by directly hitting the enter button on your keyboard. 
- If you type something other than the project name, you can also delete the project by hitting the enter button.

**Version information**
 - OS: macOS 10.15.5
 - ASReview version 0.9.5+6.g094acc0

**Comment by J535D165** [comment]
Thanks for reporting, what's your browser? I can't reproduce. Everything works like expected in Chrome.   

![localhost_3000_](https://user-images.githubusercontent.com/12981139/85747753-d7b77500-b707-11ea-9e9d-357a19dff469.png)

**Comment by terrymyc** [comment]
Yes, it works as expected in Chrome from my side as well, but it doesn't work in Safari.

**Comment by J535D165** [comment]
Can you try to fix this one (low priority)?

**Comment by terrymyc** [comment]
I will give it a try :)
