### ISSUE TITLE
Implement progress bar in simulation mode

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#345]
As far as I know, there is no progress indicator in the simulation mode. This is useful imo, especially for first time users because they don't know how much time it will take on average. 

I think it is quite straightforward to implement something like https://tqdm.github.io/.  @qubixes @GerbrichFerdinands what are your thoughts?

**Comment by GerbrichFerdinands** [comment]
That is a great idea!

I think the challenge here is in correctly estimating the remaining time.
Typically, retraining the model for the first 10% of labeling decisions will be much faster than for the last 10% of decisions. 

To me it looks like we could use `ema` from tqdm for this. (ema = Exponential moving average: smoothing to give progressively lower weights to older values)

Can this be easily combined with my feature request of logging the retraining time in the simulation mode?

**Comment by J535D165** [comment]
Hmm sounds interesting. I did not think about time in that way :) 

I was thinking about showing the iteration number (relative to the total number of iterations). That is easy to determine. Like in tensorflow https://www.tensorflow.org/addons/tutorials/tqdm_progress_bar

**Comment by qubixes** [comment]
Personally, I prefer either showing the iteration number, or cooking up something more advanced where we use benchmarks to figure out some scaling/performance numbers. I think the intermediate solution of doing smoothing/extrapolation runs into the danger of misleading users, since at the start they might think it's fast and then get progressively more disappointed with the time it takes to run the simulation...

**Comment by J535D165** [comment]
@qubixes I do agree on showing the iteration number. For now, this would be a great addition. In the nearby future, we will have a look at the more advanced options as proposed by you and @GerbrichFerdinands! Can you do a PR? Making use a an external dep is preferred because there can be some platform dependent things in making such a progress bar.

**Comment by Rensvandeschoot** [comment]
I also agree with @qubixes to show iteration number (plus total). Is there already a PR implementing this?
