### ISSUE TITLE
Keyboard shortcuts not displayed in settings menu

### ISSUE THREAD

**Issue by laurienmeijer** [asreview/asreview#351]
**Describe the bug**
Hi ASReview team,

The 'Help' section says to enable keyboard shortcuts in the 'Settings' menu, but that option is not in the menu for me.

**To Reproduce**
1. Go to Home, Project Dashboard, or 'Start reviewing' on any review.
2. Click on 'Settings'.
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/72145261/94694776-7a017d00-0335-11eb-9b26-010425e1cdc6.png)

**Version information**
 - OS: Windows 10
 - Browser: Chrome
 - ASReview version: 0.11

**Comment by Rensvandeschoot** [comment]
Dear laurienmeijer,

Many thanks for using ASReview!

The shortcuts have only been implemented in version 0.12, see https://github.com/asreview/asreview/releases/tag/v0.12

So, what you should do is to upgrade your version of the software, see for detailed instructions https://asreview.readthedocs.io/en/latest/installation.html, or in the CMD simply type 

`pip install --upgrade asreview`

Hope this helps to solve your issue, and if not, do let us know!

best
Rens

**Comment by laurienmeijer** [comment]
Hello Rens,

Sorry, I didn't realize I was behind on updates!
Works perfectly now - thanks for the quick response.

Kind regards,
Laurien
