### ISSUE TITLE
Simulation - Deterministic model results in different recall curves when not seeded

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#352]
The CLI suggests that there are 2 seeds available: one for the model and one for the prior knowledge. 

```
  --seed SEED           Seed for models. Use integer between 0 and 2^32 - 1.
  ...
  --init_seed INIT_SEED
                        Seed for setting the prior indices if the --prior_idx option is not used. If the option --prior_idx is used with one or more index, this option is ignored.
```

Running a simulation with both seeds will result in identical results. 

```
asreview simulate hall -s result_run_3.h5 --init_seed 1 --seed 1
asreview simulate hall -s result_run_4.h5 --init_seed 1 --seed 1

asreview plot result_run_3.h5 --type 'inclusion' -o plot_run_3.png
asreview plot result_run_4.h5 --type 'inclusion' -o plot_run_4.png
```

![plot_run_4](https://user-images.githubusercontent.com/12981139/94785169-7b7f8380-03cf-11eb-9070-6c82a67b0596.png)
![plot_run_3](https://user-images.githubusercontent.com/12981139/94785165-7ae6ed00-03cf-11eb-8989-c3de0d3f858b.png)

The default model is the deterministic NB model. So I thought I could skip the --seed value. However, this results in different results. Any thoughts?

```
asreview simulate hall -s result_run_1.h5 --init_seed 1
asreview simulate hall -s result_run_2.h5 --init_seed 1

asreview plot result_run_1.h5 --type 'inclusion' -o plot_run_1.png
asreview plot result_run_2.h5 --type 'inclusion' -o plot_run_2.png
```

![plot_run_1](https://user-images.githubusercontent.com/12981139/94785260-a8339b00-03cf-11eb-8b36-3e9bcadb9f93.png)
![plot_run_2](https://user-images.githubusercontent.com/12981139/94785262-a964c800-03cf-11eb-9259-b52f5d58f765.png)

**Comment by GerbrichFerdinands** [comment]
My first thought: what about the Dynamic Resampling of the training data? 
There is a random component in sampling from the labeled data.

**Comment by J535D165** [comment]
That was my first thought as well. But this issue was merged and released: https://github.com/asreview/asreview/pull/316 https://github.com/asreview/asreview/releases/tag/v0.12. 

This is an overview of my versions:

```
jonathans-mbp:bug_test jonathan$ asreview simulatie -h
usage: asreview [-h] [-V] [subcommand]

Automated Systematic Review (ASReview).

positional arguments:
  subcommand     The subcommand to launch. Available commands:
                 
                 oracle [asreview-0.12]
                     Graphical user interface for ASReview.
                 
                 simulate [asreview-0.12]
                     Simulate the performance of ASReview.
                 
                 web_run_model [asreview-0.12]
                     Internal use only.
                 
                 plot [asreview-visualization-0.2.1]
                     Plotting functionality for logging files produced by ASReview.
                 
                 stat [asreview-statistics-0.3.2]
                     Generate statistics on datasets and ASReview state files.

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  print the ASR version number and exit
```

**Comment by GerbrichFerdinands** [comment]
Even though we do not query random record anymore, there is still some random sampling going on when a training dataset is sampled from all the labeled records. In `asreview/balance_strategies/double.py`, part of the training data set is sampled at random: 

   ```
 # Sample records of ones and zeroes
        one_train_idx = fill_training(one_idx, n_one_train, self._random_state)
        zero_train_idx = fill_training(zero_idx, n_zero_train,
                                       self._random_state)

def fill_training(src_idx, n_train, random_state):
    """Copy/sample until there are n_train indices sampled/copied.
    """
    # Number of copies needed.
    n_copy = np.int(n_train / len(src_idx))
    # For the remainder, use sampling.
    n_sample = n_train - n_copy * len(src_idx)
```
It happens in `fill_training`: 

```
    # Copy indices
    dest_idx = np.tile(src_idx, n_copy).reshape(-1)
    # Add samples
    dest_idx = np.append(dest_idx,
                         random_state.choice(src_idx, n_sample, replace=False))
    return dest_idx

```

And also the training dataset is shuffled after it has been put together.

**Comment by J535D165** [comment]
Oke, makes sense. Clarification of the documentation will do, isn't it? 

```
  --seed SEED           Seed for the active learning cycle (classifiers, balance strategies, 
                        and query strategies). Use integer between 0 and 2^32 - 1.
```

**Comment by Sasafrass** [comment]
I'm assuming nobody would use 2^32-1 as a random seed, but wouldn't that lead to an overflow in a signed int? UInts go to 2^32-1, signed ints go up to 2^31-1. Just being a nasty fuck here

**Comment by qubixes** [comment]
I seem to remember having actually tested it... I don't think the number should be cast to a signed int though. From the internet it looks like Python dynamically switches C types depending on the value of the number, so it should cast to a 64-bit signed integer I would think.

**Comment by Sasafrass** [comment]
That's very interesting, thanks! Gah, dynamic typing tho

**Comment by J535D165** [comment]
Any one interested in doing a PR on this? (the docs)
