### ISSUE TITLE
Add option to click to full text

### ISSUE THREAD

**Issue by Sybren-UU** [asreview/asreview#355]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When scrolling through the articles it is not always possible to click to full text.

**Describe the solution you'd like**
Make sure there is a link that directs to the full text of the article.

**Describe alternatives you've considered**
Maybe a link to the doi, or the APA citation of the article so it is possible to look up the article manually.

**Teachability, Documentation, Adoption, Migration Strategy**
People that do a systematic review want to read the full text to check if the article meets the standards to include the article in their systematic review.

**Comment by Rensvandeschoot** [comment]
Dear @Sybren-UU, thank you for pointing this out to us!
We already show a hyperlink whenever the field for DOI-numbers is available. This is, however, not yet documented.
