### ISSUE TITLE
Error while training model after re-uploading dataset

### ISSUE THREAD

**Issue by laurienmeijer** [asreview/asreview#360]
Hi ASReview team,

After using ASReview for a while I realized there were still many duplicate records in my dataset that weren't recognized by my reference management software. I didn't want to lose my progress so I downloaded the Excel spreadsheet of results, manually removed the duplicates, and uploaded it again (in a new project). I named the column that indicates which records I had previously labeled (ir)relevant 'included', as recommended in the FAQ.

Uploading the file works, and ASReview correctly recognizes the 'included' column, displaying the correct numbers under 'prior knowledge'. I set the active learning model to the default settings (Classifier:
Naïve Bayes; Query strategy: Max; Feature extraction: tf-idf).

Clicking 'Finish' results in an endless loading icon on 'training model' and the following error message:

_An error occured. Please send an email to asreview@uu.nl or file an issue on GitHub.
Error message
index 6323 is out of bounds for axis 0 with size 6077_

(I have tried it a couple of times and the 'index' number sometimes changes, but is always greater than 6077, which is the number of records in my dataset).

If anyone knows how to solve this, it would be much appreciated!

Thank you in advance,

Kind regards,
Laurien Meijer

**Comment by Rensvandeschoot** [comment]
Dear @laurienmeijer 

Many thanks for reporting this issue! 

Could you share your file with us via asreview@uu.nl so we can run some tests to see what went wrong? 

We will come back to you as soon as possible (since you are probably in the middle of your research)

best
Rens

**Comment by laurienmeijer** [comment]
Sent, thank you in advance!

**Comment by Rensvandeschoot** [comment]
Great!
It appears that if you delete the column titled 'record_id' all works fine. If you do so, you can continue with screening your papers. We will leave this issue open till we found a better solution.

thanks again for letting us know!
best
rens

**Comment by J535D165** [comment]
For the sake of completeness, the issue was resolved by deleting the `record_id` column. It seems like there is a conflict between the use of `record_id`'s and row numbers. This seems to be a bug. 

I'm linking issue https://github.com/asreview/asreview/pull/353.

**Comment by GerbrichFerdinands** [comment]
This might be related to a feature/bug in simulation mode: 

 @qubixes mentioned in #353:

> "List of record ids used as the initial inclusions/exclusions for the simulation. In the presence of a column "record_id", these will be used for this purpose. Otherwise they are sequential in the order that records occur, starting from 0. For example, in a csv/xlsx file the first row with data will have a record_id of 0, etc."

I experienced that this is not the case. When simulating in presence of a column `record_id`, ASReview will still treat `prior_idx` as row indices instead of the values in `record_id`. Furthermore, ASReview overwrites the record_id's in the state file with the row indices. I didn't notice this behaviour before since my `record_id` columns were always equal to the row indices.
