### ISSUE TITLE
Better contrast in dark mode

### ISSUE THREAD

**Issue by Sybren-UU** [asreview/asreview#362]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In dark mode the contrast is sometimes hard to read, especially when starting a project the text is brown with a black background, the doi is also brown with a black background

**Describe the solution you'd like**
It would be nice if the contrast would get better. So no brown text with a black/grey background in dark mode. The overal contrast is also low, some users in the usability tests thought this could be higher.

**Why would you like to have this feature**
Especially in dark mode brown text with a grey/black is hard to read. The overall contrast is fine, but also low.

**Comment by J535D165** [comment]
Closed via #531
