### ISSUE TITLE
'Start reviewing' button doesn't change to 'Continue reviewing'

### ISSUE THREAD

**Issue by GerbrichFerdinands** [asreview/asreview#365]
**Describe the bug**
The project dashboard has a button called 'start reviewing'.
When the user already reviewed some records, I would expect this button to change to 'continue reviewing'.

**To Reproduce**
1. Create new project
2. Click 'start reviewing' 
3. Screen a couple of records
4. Go to project dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/45358236/95302505-55039180-0882-11eb-8836-e87b5d779b04.png)

**Version information**
 - OS: macOS
 - Browser: Chrome
 - ASReview version v0.13

**Comment by J535D165** [comment]
Thanks for reporting. I had a look at this one before. It turns out to be a bit of a challenge to implement this without adding hacky snippets of code. 

It will be a lot easier to implement after https://github.com/asreview/asreview/pull/334 is merged. I happy to work at this issue thereafter.

**Comment by terrymyc** [comment]
Resolved via #688
