### ISSUE TITLE
Error handling and notification

### ISSUE THREAD

**Issue by MartijnUX** [asreview/asreview#367]
**Describe the bug**
The user gets a error message within the dataset upload screen.
Helping the user by communicating what the user should or can do.

**To Reproduce**
1. Go to new project
2. Fill in Step 1
3. Click Next
4. Upload a corrupt file

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/45943709/95337015-ad9e5300-08b1-11eb-9f85-877d54f9e771.jpg)

**Version information**
 - OS: Windows
 - Browser Chrome
 - ASReview version .13

**Comment by J535D165** [comment]
Thanks for reporting. 

At the moment, there are only 2 errors available I think: https://github.com/asreview/asreview/blob/2046f4340b15b7984fe17de57ea44cc24f7fa905/asreview/data.py#L559-L561 and https://github.com/asreview/asreview/blob/2046f4340b15b7984fe17de57ea44cc24f7fa905/asreview/io/utils.py#L85-L86. 

I think we need additional errors, more verbose and better representation in the front-end.

**Comment by Rensvandeschoot** [comment]
For the meantime, can we add a hyperlink to the documentation with more info on preparing datasets?

**Comment by MartijnUX** [comment]
@J535D165 Is there a general error message available right now? Should be something like;"Oeps, something went wrong. You can go to our `documentation` or try again." Suggestion2; create a dialog window for error messages or the "notification pattern". This way it will always be the same for the user. Well done for the specific errors! Users love you!

**Comment by J535D165** [comment]
It makes sense to have such a generic error. I have been working on fixing some technical challenges regarding the errors in #391. This will make it easier to have specific errors, as well as unhandled errors. For now, I think we have to wait with big changes before #369 is merged, so let's add a link to the documentation. PR #391 will be followed by more structural changes to the handling of errors in ASReview LAB.

**Comment by terrymyc** [comment]
Resolved via #688
