### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by Suburbreverberation** [asreview/asreview#382]
When I click on "Export this project" a message in a new page says "Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Version information**
 - Windows 10

**Comment by J535D165** [comment]
Hi @Suburbreverberation, is there an error message in the terminal? And how many records does the dataset have? Does the export result option work?

**Comment by Suburbreverberation** [comment]
Hi, thank you for your answer. There are 461 records. The problem occurred with all the three projects I did. The download results works well but not the export.



[doc1.docx](https://github.com/asreview/asreview/files/5392223/doc1.docx)

**Comment by J535D165** [comment]
Can you share the version of the software (see left menu)? Can you copy the content of the terminal?

**Comment by Suburbreverberation** [comment]
The content of the terminal is in the docx attached in the previous message. version ASReview LAB 0.13

**Comment by J535D165** [comment]
@Suburbreverberation, sorry for the inconvenience. This is a bug in ASReview version 0.13. We are working on a fix, but it takes a little longer. The fix will be available before the end of this week.

**Comment by Suburbreverberation** [comment]
No problem, thank you for your answer. Do I need to download ASReview again once the problem will be solved?

**Comment by GerbrichFerdinands** [comment]
@Suburbreverberation once the problem is solved, you can upgrade ASReview by running

`pip install --upgrade asreview`

**Comment by J535D165** [comment]
Thanks a lot for reporting this bug. You can upgrade right now.

**Comment by Rensvandeschoot** [comment]
Well done @J535D165 !!

And many thanks @Suburbreverberation for reporting this bug! Do let us know if you experience any more problems. And if not: enjoy working with ASReview!!
