### ISSUE TITLE
More options than only mark an article as relevant and irrelevant

### ISSUE THREAD

**Issue by Sybren-UU** [asreview/asreview#387]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Sometimes users are not sure if the article is relevant or not and they want to think about it a little bit more or discuss it with a colleague. In other situations an article can be very relevant and then they want ASReview to show more articles like that, and be able to find the article again easily.

**Describe the solution you'd like**
An option to mark an article as uncertain and be able to make the decision later. The super relevant option could be an option during the screening proces when users think the article is more relevant than the other articles marked as relevant.

**Why would you like to see this feature**
Currently there are only two options relevant and irrelevant. But in reality there are more levels of how relevant an article is, an article can be very relevant and the user could be uncertain about if the article is relevant or not.

**Comment by Rensvandeschoot** [comment]
@Sybren-UU Thanks for reporting! We will add more information in the documentation of the next release. In the future someone might want to help us out with adding the options:

'postpone decision' => the next record in the queue will be shown and the postponed record will be moved back to the pool of unlabeled records. This would solve your issue, but most probably in the next iteration the same record will show up as most relevant... 

another option is 
'remove record' => it might be the record does not belong in the pool and should be deleted. This option should remove the record and re-train the model with the deleted record.

**Comment by J535D165** [comment]
The notes field can be very helpful in the mentioned examples. Feel free to reopen the issue (and maybe be a bit more specific on the proposed solution).
