### ISSUE TITLE
Test browser compatibility

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#395]
ASReview LAB is extensively tested in the Chrome browser. It is known that ASReview LAB works well in some other (desktop) browsers.  In this PR, we will test the functionality of ASReview 0.13 or 0.14 in the following browsers (check if everything works fine, post comment or issue otherwise):

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Microsoft Edge
- [x] Safari

**Comment by terrymyc** [comment]
Tested in Safari. I don't see any issue.

**Comment by J535D165** [comment]
Thanks, @Sybren-UU will test Edge. Firefox is left.

**Comment by paperbag2449** [comment]
Tested today on Firefox. No problems whatsoever that I could identify.

**Comment by J535D165** [comment]
Thanks @paperbag2449.

**Comment by Sybren-UU** [comment]
Tested Edge. It works well in Edge. The undo button stays longer on the screening page than in Safari, this is good because in other browsers the undo button goes away too fast sometimes. Importing and exporting projects works.

**Comment by J535D165** [comment]
Thanks @Sybren-UU. @emielvdveen any idea how this is possible?

**Comment by emielvdveen** [comment]
@J535D165 Hmm that's strange. The Material UI `Snackbar` has a `autoHideDuration` which is set to 6s. Could it be that something else triggers the snackbar to hide somehow?

**Comment by SagevdBrand** [comment]
In a usability test, it was found that the software doesn't work in Edge. Tried to replicate, but Edge seems to work just fine (tested both on windows and mac).

**Comment by J535D165** [comment]
Thanks for reporting @SagevdBrand. Let's flag that one as a false positive.
