### ISSUE TITLE
Documentation on how to add previous labeling decisions to your project

### ISSUE THREAD

**Issue by GerbrichFerdinands** [asreview/asreview#398]
## Feature Request
I request more documentation on how to include previous decisions to your ASReview project. 
So actually, the feature is already there but lacks documentation.
This has been requested (and used) several times now, most often when a user wants to: 

- Switch from screening in another tool to screening with ASReview
-  Updating an existing systematic review with more recent publications

The idea is that you want to include decisions you've already made prior to setting up your project.

Currently, this can be done by merging your dataset with labeled and unlabeled publications via Excel for example. Your dataset should contain a column, called `label_included` which is filled with 1's or 0's for the publications that you have already screened, and is empty for the publications that you still need to screen using ASReview. 

**Describe the solution you'd like**
We can create an extra section called **Add previous labeling decisions to your project** under the [Datasets page](https://asreview.readthedocs.io/en/latest/datasets.html#) on RTD. 

The section should consist of two parts. The first part explains that (and how) ASReview can use previous labeling decisions. The second part explains how one should construct such a dataset. I think a screenshot or two that demonstrate how this should look in Excel would be helpful. 

We can use the information that is currently available: 
- In the FAQ, [here](https://github.com/asreview/asreview/blob/master/docs/source/faq.rst#i-already-started-labeling-before-i-came-across-asreview-how-can-i-keep-my-former-screening-decisions-when-starting-a-new-project-in-asreview) and [here](https://github.com/asreview/asreview/blob/master/docs/source/faq.rst#related-question-how-can-i-add-more-publications-while-i-are-already-started-screening-in-asreview): 
    - **I already started labeling before I came across ASReview. How can I keep my former screening decisions when starting a new project in ASReview?** *You can keep your former labeling decisions by adding an extra column in your dataset called 'included' or 'label_included'. In this column, you can indicate previous screening decisions on records with 0s (irrelevant) and 1s (relevant). ASReview will use this information to train the model.*
    - **Related question: How can I add more publications while I are already started screening in ASReview?** *You can export the results of ASReview you have so far and add your new publications to this file. Make sure that for your new publications the column included is empty and rename or delete the column of record_id. This latter will save you from running into errors. Then simply import this updated file to ASReview and you can continue the screening process.*
- In issue #360. Note that this issue is still open and that this piece of documentation should elaborate on how to avoid this issue!

**Describe alternatives you've considered**
Another option is to write a short blogpost on this. Then we are able to give a bit more detail on possible use cases and implementations. But for now I think a short and technical explanation is enough. 

Ideally, this feature is implemented in the frontend in which you can simply upload a labeled and an unlabeled dataset, which are then automatically merged by ASReview.

**Comment by J535D165** [comment]
Thanks for your detailed description of the problem. @Rensvandeschoot added a few sentences on this in PR #393. I do agree that there needs to be extensive documentation on this. Also with a clear explanation of oracle and simulation differences. I think we need to work on this in small steps. It is quite some work.

**Comment by Rensvandeschoot** [comment]
I will add this as a feature in the new documentation, at least the oracle part

**Comment by Rensvandeschoot** [comment]
A description of this feature has been added to the new documentation which will be released with the new version. Shall we close this issue and open a new issue for the option to upload multiple datasets (because this would be a very nice feature to have!)

**Comment by J535D165** [comment]
I'm fine with closing this issue. I will close it via the upcoming PR on the documentation.

**Comment by Rensvandeschoot** [comment]
@GerbrichFerdinands can you start a new issue on the option to upload multiple databases? thanks!
