### ISSUE TITLE
Download review result screen doesn't disappear after clicking on download 

### ISSUE THREAD

**Issue by Sybren-UU** [asreview/asreview#407]
**Describe the bug**
When clicking on download results the menu for downloading doesn't disappear automatically when the downloading starts

**To Reproduce**
Steps to reproduce the problem:
It doesn't always happen but it happens occasionally when clicking on download results the screen stays on the page while the download already began or even finished

**Screenshots**
<img width="1440" alt="Download results" src="https://user-images.githubusercontent.com/60712710/99151378-09bb7a80-269b-11eb-9a26-cffad219a72e.png">
**Version information**
 - OS: Mac OS, during the experience test I think windows
 - ASReview version [ 0.13.2]

**Additional context**
This happened during a user experience tets

**Comment by Rensvandeschoot** [comment]
@J535D165 have you an idea what could have caused this behaviour?

**Comment by J535D165** [comment]
The dialog remains open when the download starts. It takes some time to prepare the data and for larger datasets, this would be confusing (to close right after clicking on download). Later on, there should be a prepare-data loader in between. There is no quick and dirty improvement I think. I think we should flag this "wont-fix", such that the focus is on the loader. And that's still a low-prio issue I think.

**Comment by Rensvandeschoot** [comment]
I agree... a loader would solve this... maybe @Sybren-UU  can file a feature request??
