### ISSUE TITLE
Getting an error the first 2 times a dataset was imported

### ISSUE THREAD

**Issue by Sybren-UU** [asreview/asreview#408]
**Describe the bug**
The first 2 times the user tried to add a file asreview gave an error. It was a .txt file. The third time it succeded 

**To Reproduce**
Steps to reproduce the problem: I wasn't able to reproduce this problem again

**Screenshots**
<img width="607" alt="Error importing a dataset" src="https://user-images.githubusercontent.com/60712710/99151786-c57da980-269d-11eb-98c6-184a70fa6429.png">

**Version information**
 - OS: [Windows]
 - ASReview version [ 0.13.2]

**Additional context**
This happened during a user experience test

**Comment by Rensvandeschoot** [comment]
@Sybren-UU Could you send us the dataset?

**Comment by Sybren-UU** [comment]
It was a dataset that the participant chose, I don't have the dataset on my computer. If this is important we could ask the participant

**Comment by Rensvandeschoot** [comment]
Could you maybe ask? Just to be sure... and then try to reproduce the error yourself first. Many thanks!!
