### ISSUE TITLE
Having an overview of the articles and decisions in ASReview

### ISSUE THREAD

**Issue by Sybren-UU** [asreview/asreview#412]
## Feature Request

**Describe the feature you would like to see?**
An option to have an overview in ASReview of what articles are relevant and irrelevant. And maybe an option to change the decision. Right now you can only see an overview of the decisions you already made and the articles when you download the results. If you just want to have a quick look this costs some time.

**How can users use this?**
Users can use this to see which articles they already marked and if there are articles that are duplicates. Having the option to also change the decision in this overview will give users the opportunity to detect mistakes they made earlier

**Comment by J535D165** [comment]
Thanks for reporting. There is a PR open on this. So this will be available in the software in the nearby future. See #406.
