### ISSUE TITLE
As an user I want to know what the shortcuts are

### ISSUE THREAD

**Issue by MartijnUX** [asreview/asreview#414]
**Describe the bug**
The user can switch on/off the shortcuts, but doesn't know what they are.
*What happened? And what did you expect to happen?*

**To Reproduce**
1. Go to 'screening page'
2. Click on 'Settings'
3. Scroll down to 'Shortcuts'
4. See, there is nog explanation there.

**Screenshots**
<img width="605" alt="image" src="https://user-images.githubusercontent.com/45943709/99538924-ebf95880-29ad-11eb-87b3-0097845aba82.png">

**Version information**
 - OS: mak
 - Browser safari
 - ASReview version 0.13.2

**Additional context**
It is possible to put it in the settings pannel, but we could also use "vertical tabs" from material-ui.
<img width="536" alt="image" src="https://user-images.githubusercontent.com/45943709/99539612-bbfe8500-29ae-11eb-9c8e-ca0a571d7cf9.png">

**Comment by terrymyc** [comment]
@MartijnUX Thanks for reporting the issue. I suggest we add a single-line description under the "keyboard shortcuts" and "undo".
Here is an example: https://material.io/design/platform-guidance/android-settings.html#label-and-secondary-text

**Comment by Rensvandeschoot** [comment]
Closed via #646
