### ISSUE TITLE
Installation problems due to issue with Numpy dependency

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#426]
Several users encounter issues with installing ASReview due to an issue with the `numpy` dependency. Numpy is an important dependency for ASReview as well as for thousands of other software packages. Especially **Windows users** are facing issues.

Potential solutions to circumvent the problems with numpy:

## Solution 1 - Downgrade Numpy

1. `pip install --upgrade numpy!=1.19.4`
2. `pip install asreview`

## Solution 2 - Use Python 3.8

1. Uninstall Python 3.9
2. Install Python 3.8
3. `pip install numpy!=1.19.4`
4. `pip install asreview`

\* `pip install` commandos should be inserted in the Command Prompt (cmd.exe) on Windows.

## Background info

The issue with Numpy is caused by an issue in the latest update of Windows. Background information on the issue and solutions can be found here https://github.com/numpy/numpy/issues/16744.

**Comment by rikvanberkel** [comment]
For me solution 1 worked, thanks

**Comment by stefanodallapalma** [comment]
Hi, I would add a third solution: use a virtual environment.

1. `virtualenv venv`
2. `source venv/bin/activate`
3. `asreview lab`
