### ISSUE TITLE
Add import option for relevant items 

### ISSUE THREAD

**Issue by FelixWdm** [asreview/asreview#450]
## Feature Request --> Import relevant items as a RIS file during project set up, prior knowledge.

**Is your feature request related to a problem? Please describe.**

- Not releated to an issues, but would help in the workflow "updating an existing systematic review" where there's a substantial set of relevant studies known that can be exported at once and that are not included in the newly found set of items to be screened.

**Describe the solution you'd like**
- During the 'Select prior knowledge' it should be possible to upload a set of relevant articles, using the same steps as uploading the data via 'From file'. It should add all these items to the project marked as 'relevant'.

**Describe alternatives you've considered**
- The alternative is to combine the set of already known relevant items with the new set that needs to be screened. and then manually lookup the articles in the total set.

**Teachability, Documentation, Adoption, Migration Strategy**

- Import option added during the select prior knowledge phase. All items in the file that will be imported must be: a. relevant to the current project. And b. not already included in the dataset that was uploaded/selected during set up.

![image](https://user-images.githubusercontent.com/49488769/103537086-01f6a600-4e94-11eb-88da-7919bf38a3cb.png)

Thank you!

**Comment by J535D165** [comment]
Thanks for reporting. Sounds like an interesting feature. Technically, this might be a fun challenge to implement. 

> And b. not already included in the dataset that was uploaded/selected during set up.

This makes sense. Otherwise, we run into record linkage challenges. 
Do you expect the additional dataset to be included in the export file?

**Comment by Rensvandeschoot** [comment]
Great suggestion @FelixWdm!
I can see why you would want this feature! Do you want to import the data in this step or in the same step where you also import the unlabelled data?

**Comment by FelixWdm** [comment]
Hi Both, @J535D165, I would expect the set to be included in the export, but that's not a must. @Rensvandeschoot both would work I guess, as long as it is clear that the imported records will be added to the unlabelled data, and should not be already included in the unlabelled data.

**Comment by Rensvandeschoot** [comment]
@FelixWdm thanks! 
Indeed, it should be made very clear for the user which subset of the data is used, stored, exported, etc etc. Therefore, I would prefer to upload data only during one single step... and then attribute different roles to the different subsets, just like you do when you submit a paper.
