### ISSUE TITLE
Add a question mark icon to find more information about the graphs

### ISSUE THREAD

**Issue by Sybren-UU** [asreview/asreview#473]
## Feature Request

**Is your feature request related to a problem? Please describe.**
During the user experience tests some users have trouble with understanding the statistics and the graphs.

**Describe the solution you'd like**
A question mark icon which users can click on to see more information about the different graphs and statistics.

**Describe alternatives you've considered**
There could also be more text in the statistics and surrounding the graphs so it is not even necessary to click on the question mark icon. I also couldn't find any clear documentation about the interpretation of the statistics and the graphs

**Teachability, Documentation, Adoption, Migration Strategy**
Users that are new to ASReview can use it to get more information very easily about the statistics without it interrupting the screening process.

**Comment by Rensvandeschoot** [comment]
@J535D165 I will draft a PR for the documentation. Let's plan the info-pop-up for v1.0, ok?

**Comment by J535D165** [comment]
Agree.
