### ISSUE TITLE
asreview lab: returns blank browser screen

### ISSUE THREAD

**Issue by tobimichigan** [asreview/asreview#488]
**Describe the bug**
*What happened? And what did you expect to happen?*

**To Reproduce**
Steps to reproduce the problem:
After setting up asreview, I ran

asreview lab on the terminal and it brings up:

**Screenshots**
![image](https://user-images.githubusercontent.com/5084987/107025455-c2302080-67a9-11eb-922f-205fda7c66b5.png)

**Version information**
 - OS: Linux 18.04
 - ASReview version [e.g. 0.6.2]

**Additional context**

`asreview/asreview_venv/lib/python3.7/site-packages/Flask-1.1.2-py3.7.egg/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
ERROR:root:index.html
`
any pointers @daob @behrica @emielvdveen @leonardovida @MathieuRietman

**Comment by J535D165** [comment]
@tobimichigan thanks for reporting and sorry for the inconvenience.

@terrymyc or @Sasafrass can you reproduce this on your Linux systems? I haven't seen this before.

**Comment by Sasafrass** [comment]
Hmm, runs for me on Ubuntu 18.04 with the latest ASReview release. Appears as if there's just no index.html in the install, so maybe it's an older version of ASReview or a faulty installation?

**Comment by tobimichigan** [comment]
@J535D165 @Sasafrass @daob @behrica 
I tried it both locally and on Google Colab.
asreview version: 0.16+5.g0c6c79e
![image](https://user-images.githubusercontent.com/5084987/107144541-123eec80-693c-11eb-8ebe-a8f81eb4f9aa.png)
![image](https://user-images.githubusercontent.com/5084987/107144552-2551bc80-693c-11eb-9c1c-657e6ea0f932.png)
![image](https://user-images.githubusercontent.com/5084987/107144585-68ac2b00-693c-11eb-8eb6-a5a40d128bd8.png)

There has to be an explanation as to why this is occurring. The error log is pointing to flask.

**Comment by leonardovida** [comment]
Hi @tobimichigan,

We recommend you to use `pip` to install asreview as it is the most straightforward method:

```
pip install asreview
# Once installed, start the application with the following command (in CMD.exe or Terminal):
asreview lab
```

The official documentation guides you through the recommended installation steps (you can find it [here](https://asreview.readthedocs.io/en/latest/intro/installation.html)) and offers other possibilities (e.g. an install using Docker or on a server).

In your case, you cloned the repository and are trying to start asreview LAB using something like `python asreview lab` without first having compiled the react components of the webapp (via `npm`). As previously said, this is not the recommended way to install it, but if you want to have it working without using `pip` you should do the following:

```
# From the root folder of the repository, compile assets:
python setup.py compile_assets
# Now that the assets are compiled, you can start the flask app with:
python asreview lab
```

**Comment by tobimichigan** [comment]
@leonardovida @J535D165 @Sasafrass @daob        Pls take a look:
![image](https://user-images.githubusercontent.com/5084987/107146507-18879580-6949-11eb-9c33-58c2d447bc21.png)


As per python setup.py compile_assets, this was the output:
![image](https://user-images.githubusercontent.com/5084987/107146563-70260100-6949-11eb-8473-0da4178b982f.png)

I hope you now see this is a real bug...pls suggest better ideas.

**Comment by tobimichigan** [comment]
@leonardovida @J535D165 @Sasafrass @daob 
The only thing that ran successfullly is the sphinx with help of make in the asreview dir that helped to generate the help files for asreview:..besides which nothing is displayed both in colab and my local machine.
![image](https://user-images.githubusercontent.com/5084987/107147057-34d90180-694c-11eb-98f9-0fd4cf8ee873.png)

![image](https://user-images.githubusercontent.com/5084987/107147045-20950480-694c-11eb-99bf-dea251ce69b6.png)

**Comment by leonardovida** [comment]
@tobimichigan If you install using `pip install asreview` to run asreview LAB you should only use `asreview lab`

If you want to build using `setup.py`

```
python setup.py install
#
python setup.py compile_assets

**Comment by tobimichigan** [comment]
@leonardovida 
The first solution returned an error
![image](https://user-images.githubusercontent.com/5084987/107149761-c9e2f700-695a-11eb-9fb6-a3a8f561baf2.png)

The second pathway worked (which involved using DockerCE, which you didn't list as a solution). Below is the product of Docker pull:
![image](https://user-images.githubusercontent.com/5084987/107149738-aae46500-695a-11eb-808d-52eaa435896c.png)

its now obvious only your Docker pull is working. You guys will need to look at the other alternative of installation as there seems to be a bug there.

**Comment by J535D165** [comment]
Hi @tobimichigan, it makes sense to add `npm install` to the build file. https://github.com/asreview/asreview/blob/0c6c79e98f867e977d5b5cda5a2d56e0aec66dac/asreview/webapp/compile_assets.sh. @tobimichigan can you test and do a PR?

Our implementation was inspired by airflow. 
- https://github.com/apache/airflow/blob/649335c043a9312ef272fa77f2bb830d52cde056/airflow/www/compile_assets.sh.
- https://github.com/apache/airflow/blob/649335c043a9312ef272fa77f2bb830d52cde056/setup.py#L89-L106

The equivalent of `yarn install --frozen-lockfile` in npm is https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable.

**Comment by george-gca** [comment]
I installed `asreview` via [pipenv](https://pipenv.pypa.io/en/latest/) on Ubuntu 23.04 and python 3.11. Basically, cloned the repo, entered and:

```bash
pipenv install -e .
pipenv run asreview lab
```

Got the same problem as previous users, the web interface only displays this:

```json
{
  "message": "index.html"
}
```

And in the terminal:

```
ERROR:asreview.webapp.start_flask:Exception on / [GET]
Traceback (most recent call last):
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/repos/asreview/asreview/webapp/start_flask.py", line 373, in index
    return render_template("index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/flask/templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gca/.local/share/virtualenvs/asreview-ulBNM-0n/lib/python3.11/site-packages/flask/templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
ERROR:root:index.html
```

Any suggestion?

**Comment by george-gca** [comment]
5000, the one that appeared in the terminal:
![image](https://github.com/asreview/asreview/assets/31376482/5d2cd553-4a17-42ee-b463-c60de596ff62)
