### ISSUE TITLE
Integration with https://core.ac.uk/ - the world's largest collection of open access research papers

### ISSUE THREAD

**Issue by jbemmel** [asreview/asreview#489]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have started to use ASReview to discover interesting research papers / knowledge about various topics. The problem is that the small, fixed set of data collections it comes with isn't likely to contain what I am looking for

**Describe the solution you'd like**
I would like there to be a plug-in which allows me to use the CORE API (https://core.ac.uk/services/api/) to create an initial set of papers to review. The API is limited to 10 pages of 100 articles each, so it's important to help the user formulate a query that returns a specific set of results. Also, some filtering of duplicates may be required.

**Describe alternatives you've considered**
I've built a small script to query the CORE API /article/search and create a .csv file with title, abstract and URL. This works, however the iteration cycle is rather long and cumbersome - it would be nicer to have it integrated as 1 experience

**Teachability, Documentation, Adoption, Migration Strategy**
I think most users will naturally understand how to leverage this new source of potential knowledge. I recently discovered CORE after having obtained ASReview and I have no affiliation or know any of their team members, but I suspect they may be interested to collaborate: https://core.ac.uk/about/#team. Both projects seem very much aligned in their philosophy

**Comment by bmkramer** [comment]
Thanks for your interest in ASReview!

Currently, ASReview is not designed to support query-based search in external databases.
The general recommendation is to perform a search in one or more external databases of choice (making use of specialized search functionalities in each system) and then import the resulting dataset in ASReview for automated screening.

(NB One suggestion for a multidisciplinary scholarly search engine that is free to access, and allows export as csv to use in ASReview, is [Lens.org](https:/. Lens includes data from Crossref, PubMed, Microsoft Academic (and some full-text from CORE) and allows export of up to 50,000 article records.  NB An account is required to enable export)

**Comment by tsaltena** [comment]
@jbemmel: Together with Rens and the ASReview team, we're working on accessing the dataset OpenAlex (the continuation of Microsoft Academic that soft-launched early 2022). If you're interested in hearing more about the pilot or using it for your usecase, please drop me a line at tijmen@idfuse.nl.
