### ISSUE TITLE
Simulation with only irrelevant priors uses more, random, prior data than given priors with prior_idx

### ISSUE THREAD

**Issue by LHofstee** [asreview/asreview#500]
**Describe the bug**
When making use of the simulation mode and the prior_idx only has irrelevant papers, the model uses more - random - prior information untill a relevant paper is found instead of only the priors given with prior_idx. It makes sense that the model needs relevant papers, but this makes that the model is different than what you think you simulated (if you do not look at the state file). A solution might be to add a warning that you did not include a relevant paper as prior.

**To Reproduce**
Steps to reproduce the problem:
- Run a simulation with only irrelevant papers as priors;
- Look in the state file at the training data used for the first itteration and the labels for result 0;
- Repeat the process with a simulation that includes a relevant paper to see the difference.

**Version information**
 - OS: Windows
 - ASReview version .14

**Comment by J535D165** [comment]
Can you open a PR to improve the documentation? Just to be sure, you get 1 random included record, isn't it? This item is returned in the command line, isn't it? I'm not sure whether a warning makes sense. Can you suggest what this should look like?

**Comment by PeterLombaers** [comment]
Laura and I were talking about this yesterday. Currently, if you don't have any relevant priors in simulation, then it just keeps on trying random papers until it hits on a relevant paper. For example, if you run a simulation on the ACE dataset with --prior_idx 0 1, then it ends up with these indices in the priors: 
[   0    1 1357 1135 1289   50 2325  442 1115  254 2504  326 1661 2070
 1947 1792 1556 2204 1657 1827 1378 1873 2265   35 2505  360  952 1970
  932 2162]

**Comment by LHofstee** [comment]
I compared what you see in the command line with what you see happening in the state file. 

When a user (accidently) gives only irrelevant records as prior knowledge – which can happen when the user e.g. forgets to correct for the indexing differences – only the by the user chosen records are returned in the command line, see the jobs file for an example. 

However, when you look into the state file, it is seen that records are chosen (randomly I think) until a relevant record pops up, see the R file for an example.

I believe this to be a problem, because you have e.g. 40 in stead of 2 priors without you knowing about it.

I think that you ideally want:
-	that you know which records are actually used as prior knowledge;
-	that it is not a random search until a relevant paper is found, but that only one extra paper is used as prior record; a relevant record.

To recreate this with the attached scripts:
-	change the path in the jobs file to the folder containing the data;
-	run the jobs file;
-	install the rhdf5 package in R;
-	change the path in the R file to the folder containing the data;
-	run the R script.
[Scripts to recreate issue 500.zip](https://github.com/asreview/asreview/files/6284855/Scripts.to.recreate.issue.500.zip)

**Comment by J535D165** [comment]
@PeterLombaers can we confirm this issue is resolved with the new state file?

**Comment by PeterLombaers** [comment]
When I try to run a simulation with only included or only excluded priors, I get
```ValueError: Not both labels available Make sure there is an included and excluded record in the priors.```
so this seems resolved to me.
