### ISSUE TITLE
Number of exclusions in json file does not match actual exclusions

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview#501]
**Describe the bug**
The number of exclusions in the json file with the results does not match the number of actual exclusions. 

**To Reproduce**
Input :

```
asreview simulate data/Unconscious_conditioning.csv -s output/simulation/Unconscious_conditioning/state_files/state_Unconscious_conditioning_10.h5 --prior_record_id 10 36 42 93 2 63 6 13 38 62 8 --seed 165
```

The result is:
```
{
  "output/simulation/Unconscious_conditioning/state_files/state_Unconscious_conditioning_10.h5": {
    "settings": {
      "model": "nb",
      "query_strategy": "max",
      "balance_strategy": "double",
      "feature_extraction": "tfidf",
      "n_instances": 1,
      "n_prior_included": 1,
      "n_prior_excluded": 1,
      "mode": "simulate",
      "model_param": {
        "alpha": 3.822
      },
```

**Version information**
 - OS: Windows
 - ASReview version v0.16

**Comment by GerbrichFerdinands** [comment]
Maybe is helpful towards locating the problem: 

It does work for me hen you use the arguments `--n_prior_included` and `--n_prior_excluded`: 

When I run a simulation where I set the number of prior inclusions and exclusions to 20: 
```
asreview simulate data/Bannach-Brown_2019.csv -s output/Bannach-Brown_2019_more_prior/simulation/run_Bannach-Brown_2019_0.h5 --n_prior_included 20 --n_prior_excluded 20 
```

I do get the correct number of priors in the asreview stat output: 
```
{
  "output/Bannach-Brown_2019_more_prior/simulation/run_Bannach-Brown_2019_0.h5": {
    "settings": {
      "model": "nb",
      "query_strategy": "max",
      "balance_strategy": "double",
      "feature_extraction": "tfidf",
      "n_instances": 1,
      "n_prior_included": 20,
      "n_prior_excluded": 20,
      "mode": "simulate",
      "model_param": {
        "alpha": 3.822
      },
```

**Comment by GerbrichFerdinands** [comment]
I think this is due to the fact that the number of prior records is only counted when they are provided from `--n_prior_included` or `--n_prior_excluded`. Not if you use `--prior_idx`:

https://github.com/asreview/asreview/blob/0c6c79e98f867e977d5b5cda5a2d56e0aec66dac/asreview/review/factory.py#L155-L166

**Comment by Rensvandeschoot** [comment]
Thanks @GerbrichFerdinands !
