### ISSUE TITLE
Parse URL to the front-end

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview#504]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Often a dataset has a field with Digital Object Identifiers. ASReview will then display the DOI with hyperlink during screening.

![](https://asreview.readthedocs.io/en/latest/_images/doi.png)

However, not for all records a DOI is often available, but often a column `url` is also available. 

@bmkramer / @boer0107: is this a standard output of ris files?

**Describe the solution you'd like**
I would propose ASReview to detect if the `doi` field is missing and then checks the`url` colum and parse the hyperlink to the front-end if available.

**Describe alternatives you've considered**
When I changed the column name `url` into `doi`, the hyperlinks did show up in the front-end, but the hyperlinks did not work. I would like to know what ASReview does under the hood with the DOI so that we can add this information to the documentation. 

![image](https://user-images.githubusercontent.com/36502709/110288252-02bccd00-7fe8-11eb-8af1-526e8a5124bf.png)

**Comment by boer0107** [comment]
The use of URL in a ris file depends on the source database. In most cases, it contains the URL of the reference in the source database, not a reference to the article. But for instance a Cochrane export might contain the URLs of registered trials which do not have a DOI.

**Comment by Rensvandeschoot** [comment]
@boer0107 Thanks! So, does it mean you think it is a good idea to detect information in the url column if doi is missing??

**Comment by boer0107** [comment]
Yes, but it won't always lead to the article. It might sometimes.

**Comment by J535D165** [comment]
Asreview detects whether the DOI is a pure DOI or URI DOI. Replacing the column name "url" by "doi" will therefore result in broken links. 

The RIS format provides both a DOI and URL field. I would propose to show both fields in lab and make a field in the settings menu to toggle them on and off. What doe you think?

**Comment by Rensvandeschoot** [comment]
Yes, I completely agree with this solution!!!

@kirstenberk would this work for you?
