### ISSUE TITLE
Project not loading in - previously working fine 

### ISSUE THREAD

**Issue by taviaevans** [asreview/asreview#521]
After opening asreview lab as normal and clikcing on the project it does not load. this happened suddenly and was previously working. 

CMD: python -m asreview lab

[ interface ] clicked on project.- gets stuck on loading page with statstics boxx loading (if click start reviewing also blank)

**Screenshots**

![ASreview](https://user-images.githubusercontent.com/60198912/111770603-e99b0280-88aa-11eb-988b-09e158e4a497.png)

**
**Version information**
 - OS: Windows
 - ASReview version most uptodate 

**Additional context**
tried to remove temp files however still getting the same problem.

**Comment by J535D165** [comment]
Sorry for the inconvenience (and don't worry). Can you run the following command?

```
asreview lab --clean_project united-review
```

https://asreview.readthedocs.io/en/latest/intro/installation.html#remove-temporary-files

**Comment by taviaevans** [comment]
Hey,

Run and still the same thing is occurring. If I load in an old exported file from the same set it works... I have a feeling there is a bug in my newer file. Not the end of the world just a few hours lost.

Best, T
________________________________

**Comment by J535D165** [comment]
Oke thanks for testing. No please wait. We have encountered the issue before and trying to avoid it. 

Please make an export of the project first (in the section Publication and export). 


Fix:
- Please go to the `.asreview` directory in your home folder (maybe you have to show hidden files). 
- Open the project `united-review`. There is a `lock.sqlite` file in there, isn't it?
- Delete this file and copy the `lock.sqlite` of another project into the `united-review` folder.

**Comment by J535D165** [comment]
If this doesn't work (I expect this to work btw), please send the file to asreview@uu.nl. We will try to investigate the issue asap.

**Comment by taviaevans** [comment]
Yes! replacing the lock.sqlite file works!

Thank you so much.
Best,
Tavia
________________________________

**Comment by J535D165** [comment]
Sometimes this happens on a unexpected shutdown of the computer. I'm looking for a fix, but haven't found one yet. Please let me know if something unexpected happened in advance. 

I will leave this issue open such that we can work on a fix.

**Comment by taviaevans** [comment]
ah okay, makes sense. Thank you again!

Best,
Tavia
________________________________
