### ISSUE TITLE
unable to import asreview results to mendeley

### ISSUE THREAD

**Issue by SV-ZZ** [asreview/asreview#586]
There are two options to download the screened results. 
1. CSV(UTF-8)
2. EXCEL

Tried importing in both formats to mendeley but, didn't work. 
Is there any way to import my screened results to mendeley and other software tools from ASReview?

**Comment by J535D165** [comment]
Thanks for your question. This is an open feature request indeed. We are working on an RIS Export option #495 and #225. The latter one also provides a workaround but requires some programming/hacking.

Do you have a list of import formats that Mendeley supports?

**Comment by SV-ZZ** [comment]
> Thanks for your question. This is an open feature request indeed. We are working on an RIS Export option #495 and #225. The latter one also provides a workaround but requires some programming/hacking.
> 
> Do you have a list of import formats that Mendeley supports?

Thanks for the reply! It was great using asreview. Never felt the screening this easy and it's really fun to use. looking forward to more advanced features that make a Systematic review process less time-consuming. 

Below is the link for all import formats that Mendeley supports.
https://data.mendeley.com/file-formats

**Comment by boer0107** [comment]
Mendeley (desktop) only supports three formats: bibtex, ris and Endnote xml: https://www.mendeley.com/guides/desktop/02-adding-documents.
We do have a workaround, which allows you to convert the csv output from ASReview into a bibtex format using R (https://github.com/asreview/asreview/issues/225)

**Comment by J535D165** [comment]
This is available nowadays. The RIS option is only available when RIS formatted data is loaded into ASReview LAB.
