### ISSUE TITLE
Allow uploads of included records into Distiller SR via Distiller SR API

### ISSUE THREAD

**Issue by behrica** [asreview/asreview#601]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We might be interested to use AsReview as a "first screening tool". But the included records should then be easy "importable" into Distiller SR. There is an API for this now in Distiller SR.

**Describe the solution you'd like**
I would see this "upload into Distiller SR" as an alternative to "Download Review Result"

**Describe alternatives you've considered**
Downloading the screening result, and uploading the "changed" CSV file to Distiller is indeed possible already know.
But a tighter integration with Distiller SR could be beneficial for teams, which use Distiller SR already.

**Comment by J535D165** [comment]
It would be nice to have integrations indeed with other software packages. Nowadays, we support 4 types of file formats for exports. With those 4 formats, we are compatible with many external software solutions in our chain. It is also possible to write extensions for other file formats via custom entry points. 

I don't feel like integration with Distiller should be on our list for the upcoming months/years. Our efforts should be focused on integrations with FOSS software solutions like Zotero. Integrations like the one proposed are still welcomed but should be developed by the vendor itself or the community. Ideally as an external extension first such that we don't have to maintain it (I don't have access to their API and I'm not gonna pay for it ever). 

Given the arguments above, I'm closing this issue. We are nevertheless open for discussion in this thread or via email.
