### ISSUE TITLE
Excel file doesn't upload

### ISSUE THREAD

**Issue by reviewerXY** [asreview/asreview#642]
When trying to upload my data file in ASReview, ASReview did not recognize my excel file. This excel file is a test-file with several papers downloaded from Web of Science. 

Can you explain what the problem is? The .xls file is attached. Thank you!

[savedrecs (1).xls](https://github.com/asreview/asreview/files/6699940/savedrecs.1.xls)

**Comment by Rensvandeschoot** [comment]
Dear @reviewerXY , thank you for reporting this!

It seems your excel file is <2013 and is saved as `.xls` instead of `.xlsx`. To solve this: open your file in Excel and save it as a newer Excel file. Then it should work!

**Comment by Rensvandeschoot** [comment]
@terrymyc is there a way to support `.xls` files as well?

**Comment by J535D165** [comment]
It is possible to support. Add `.xls` to 
https://github.com/asreview/asreview/blob/c03eb4ba380cc817819abab78d8ee96bee340f4d/setup.py#L138-L146

However, I think we shouldn't support this. It's outdated and it's a closed source format.
