### ISSUE TITLE
Failed to load Benchmark dataset. 

### ISSUE THREAD

**Issue by geswapan** [asreview/asreview#644]
When I try to load benchmark dataset - error message: Failed to load benchmark dataset
Python 3.9
Mac OS: 10.15.7 Catalina
Asreview 0.17

**Comment by Rensvandeschoot** [comment]
Dear @geswapan , thank you for reaching out to us! To help you further we would need the output shown in the terminal so that we can locate potential error messages.

**Comment by J535D165** [comment]
A more informative error message in the front-end would be nice. As there is no response, I'm closing the issue. Feel free to reopen.
