### ISSUE TITLE
Why is importing .xlxs files not supported?

### ISSUE THREAD

**Issue by absyedd** [asreview/asreview#703]
**Describe the bug**
*What happened? And what did you expect to happen?*

**To Reproduce**
Steps to reproduce the problem:

**Screenshots**

**Version information**
 - OS: [e.g. Windows]
 - ASReview version [e.g. 0.6.2]

**Additional context**

**Comment by J535D165** [comment]
Are you sure the file is xlxs and not xlsx?

**Comment by Rensvandeschoot** [comment]
@absyedd We support many different file formats, see https://asreview.readthedocs.io/en/latest/intro/datasets.html#data-format including `.xlsx`. If your file fails to upload in the software, can you send us screenshots of the error messages in the terminal?
