### ISSUE TITLE
Incomplete titles do not return prior inclusion as expected

### ISSUE THREAD

**Issue by SagevdBrand** [asreview/asreview#715]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When trying out the exploration mode on the PTSD data the following occurred:
At the step of providing prior information, using the relevant papers as described [here](https://asreview.readthedocs.io/en/latest/lab/exploration.html), I could not retrieve one of the records, when only providing the partial title: "latent growth mixture modeling". While the full title is "A Latent Growth Mixture Modeling Approach to PTSD Symptoms in Rape Victims"

![image](https://user-images.githubusercontent.com/64579032/131342895-b1eac81b-b5c9-4262-8012-bfd0d24bec57.png)

**Describe the solution you'd like**
Perhaps it would be possible to implement a scrollable screen, so you can  scroll down the list of found records within the software, instead of the first 10?

**Describe alternatives you've considered**
Extra documentation in Exploration mode to use the full title instead of a part of the title.

**Comment by SagevdBrand** [comment]
Added documentation in read the docs 📓 , see #739 and more specifically this commit: https://github.com/asreview/asreview/pull/739/commits/378ba3a78a118c0c0cbe72c3d4af500cac533e38

**Comment by Rensvandeschoot** [comment]
Solved with https://github.com/asreview/asreview/pull/739
