### ISSUE TITLE
Installing ASReview backend fails on Apple M1 chip

### ISSUE THREAD

**Issue by ottomattas** [asreview/asreview#738]
**Describe the bug**
Trying to install ASReview in [DEVELOPMENT mode](https://github.com/asreview/asreview/blob/master/DEVELOPMENT.md) fails on an Apple M1 chip. Process takes about 1 hour to complete.

**To Reproduce**
Steps to reproduce the problem:
1. Pull the latest code from the repository
2. Navigate to the repository locally
3. `pip install -e .`

**Version information**
 - OS: macOS Big Sur Version 11.5.2 (20G95)
 - MacBook Pro (13-inch, M1, 2020)

**Additional context**
Full [CLI output](https://github.com/asreview/asreview/files/7153812/cli_output.txt.zip) attached as a zip container.

**Comment by ottomattas** [comment]
From the looks of it, there are three packages that need a workaround - `h5py`, `scikit-learn`, `scipy`.

Relevant section from the end of CLI output:
```
Successfully built gevent greenlet pandas zope.interface
Failed to build h5py scikit-learn scipy
Installing collected packages: scipy, numpy, Jinja2, itsdangerous, click, zope.interface, zope.event, scikit-learn, pytz, python-dateutil, greenlet, flask, et-xmlfile, xlrd, sklearn, rispy, pandas, openpyxl, h5py, gevent, flask-cors, dill, asreview
```

**Comment by ottomattas** [comment]
There is a quick workaround, using [miniforge](https://formulae.brew.sh/cask/miniforge).

```
# Install miniforge
% brew install miniforge

# Create environment
% conda create --name asreview_m1

# Initialise (zsh) shell
% conda init zsh

# Source (zsh) shell directly
% . ~/.zshrc

# Activate environment
% conda activate asreview_m1

# Install packages which fail to install via pip
% conda install h5py scipy scikit-learn

# Install asreview
% pip install -e .

# Delete the environment, in case you need to clean up afterwards
% conda deactivate
% conda env remove -n asreview_m1
```

This workaround was inspired by [Hendrik Erz](https://github.com/nathanlesage), a researcher and an Open Source contributor. If you want to read up on the method proposed here, you can see his [blog post](https://hendrik-erz.de/post/update-setting-up-python-numpy-and-pytorch-natively-on-apple-m1) on the issue.

**Comment by MarielleZZ** [comment]
Starting with a git clone + cd on asreview and proceeding with the workaround above was successful for me:

`git clone https://github.com/asreview/asreview.git
cd asreview

brew install miniforge
conda create --name asreview_m1

conda init zsh
. ~/.zshrc
conda activate asreview_m1
conda install h5py scipy scikit-learn
pip install -e .
conda deactivate
conda env remove -n asreview_m1`

**Comment by ottomattas** [comment]
Thanks for reporting back and confirming the proposed solution @MarielleZZ!

**Comment by hjiajing** [comment]
I didn't address this M1 issue following the above workaround. But I ran `pip3 install asreview` and it worked fine. Then I ran `asreview lab`, the asreview ran successfully. 😂

**Comment by pietervandekerckhove** [comment]
Thank you @hjiajing , it worked for me as well in this way :)
