### ISSUE TITLE
I can not continue my project and my stats were lost.

### ISSUE THREAD

**Issue by Qifrey** [asreview/asreview#740]
**Describe the bug**
I have been making a screening project since 2 weeks ago. Yesterday I noticed that the asreview lab was slow but nothing changed. Today, when I tried to open my stats they were not available to me just like my project.

**To Reproduce**
asreview lab command

**Screenshots**
**1th -**
![image](https://user-images.githubusercontent.com/86391839/133435294-3d58ebc5-79b8-477d-9326-e9f5b2d46a54.png)

**2th -** when I look at the web page:
![image](https://user-images.githubusercontent.com/86391839/133435414-010c22dd-2f93-44f5-b887-80fdce226cb4.png)

**3th -** when I select the project - without my stats:
![image](https://user-images.githubusercontent.com/86391839/133435548-d814fd9c-1969-462d-9e33-1e3112a6fe12.png)

**4th -** when I select the start reviewing option:
![image](https://user-images.githubusercontent.com/86391839/133436016-86a3c7a9-adf9-4441-aef6-d60666565cef.png)

**5th -** the prompt after this:
![image](https://user-images.githubusercontent.com/86391839/133436160-73b5011a-516c-437a-94b4-e8a98ff6b277.png)

**6th -** when I come back to the home page:
![image](https://user-images.githubusercontent.com/86391839/133436792-d2774064-e98e-48e8-a2a8-f4d1cd8acfdc.png)

**Version information**
 - OS: Windows 10 Home Single Language - 21H1
 - ASReview version 0.17.1

**Comment by J535D165** [comment]
Can you run 

```
asreview lab --clean-all-projects
```

If this doesn't solve the issue, can you still export the project? If so, please send the project to asreview@uu.nl such that we can try to reproduce it.

**Comment by Qifrey** [comment]
> Can you run
> 
> ```
> asreview lab --clean-all-projects
> ```
> 
> (this is a safe operation btw)
> 
> If this doesn't solve the issue, can you still export the project? If so, please send the project to [asreview@uu.nl](mailto:asreview@uu.nl) such that we can try to reproduce it.

**Comment by Qifrey** [comment]
I tried and did not worked.
![image](https://user-images.githubusercontent.com/86391839/133443395-e87f0def-8b59-4c77-9fde-03a5decfa064.png)


I also tried to export, but nothing happens. You can see here:
![image](https://user-images.githubusercontent.com/86391839/133443050-d6f26846-88d4-4b38-9930-8706f5a99cac.png)

**Comment by J535D165** [comment]
Can you go to your home folder and navigate into the `.asreview` folder. There is a folder named "screening" in there. Can you zip that folder and send it to us via email?

**Comment by Qifrey** [comment]
Yes, just a second.

**Comment by Qifrey** [comment]
I sent the email yesterday, did you received?  
I have tried to opened in another web browser and nothing change. Moreover, I uninstalled it but it had no effect. Help, I need it to finish my undergrad thesis.

**Comment by SagevdBrand** [comment]
Hi @Qifrey, 
I have just send you an email about this 👍

**Comment by Qifrey** [comment]
The team are just amazing, my project is working again now! Thank you for the help. <3

**Comment by SagevdBrand** [comment]
Yay, glad it is working now! good luck with screening!

Thank you @terrymyc  for your help!!

**Comment by Qifrey** [comment]
Thank you Terry! :)
