### ISSUE TITLE
Unify creating issues in ASReview repositories

### ISSUE THREAD

**Issue by ottomattas** [asreview/asreview#744]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, some repositories (e.g https://github.com/asreview/asreview/issues/new/choose) have issue templates while others do not (e.g https://github.com/asreview/asreview-wordcloud/issues/new). So there is not one clear way of reporting/handling issues.

**Describe the solution you'd like**
Add the same templates to all repositories if possible. Exceptions should be kept to a minimum to lower the overhead for managing those templates.

**Describe alternatives you've considered**
Somehow direct all issues to one repository while this might be confusing to the community and users.

**Teachability, Documentation, Adoption, Migration Strategy**
We can then just open an issue in any repository and the process is unified. There is nothing extra that the user should do, really. It would just look the same across the organisation, also helping the community manage those repositories more uniformly.

**Comment by J535D165** [comment]
Yes, sounds like a good plan. I prefer to improve the existing template first. 

For example the version information: We can add something like "Run `asreview -h` and copy-paste the output here". This is more generic because it also works for the extensions.

I'm assigning you to this issue.

**Comment by ottomattas** [comment]
Hi all,

I have collected the currently used templates into a Google Docs document for editing: [Internal GDoc](https://docs.google.com/document/d/15kk95ubw_ZjAS0gE7h9bgtFAEHo2bO8vOa_GpZzDP0w/edit#heading=h.rdj7unulabtv).

Can you make your additions there, @J535D165? After that, we can move forward with populating [all the repositories in the organisation](https://github.com/orgs/asreview/repositories).
