### ISSUE TITLE
Not enough random indices to sample from.

### ISSUE THREAD

**Issue by Sitong22** [asreview/asreview#754]
I have uploaded the ris. file(exported by Endnote).When I chose random, it said Not enough random indices to sample from.

**Comment by SagevdBrand** [comment]
Hi there @Sitong22 ,

Thank you for reaching out!
Could you check how many citations are in the .ris file? (You can open it in notepad.)
It could very well be that when exporting from EndNote, only one citation was selected and therefore only that one was exported. This might also explain issue #755.

If this is not the case, could you please send your .ris file to asreview@uu.nl?

Hope this helps!

All the best,
Sofie

**Comment by Rensvandeschoot** [comment]
I am closing this issue because it has been solved with the suggestion of @SagevdBrand . 

@Sitong22 feel free to post a question in our [discussion feed](https://github.com/asreview/asreview/discussions) if you need additional assistance with exporting a `.ris` file from Endnote.
