### ISSUE TITLE
Search Function did not work in "Select prior knowledge"

### ISSUE THREAD

**Issue by Sitong22** [asreview/asreview#755]
No matter what "title" I searched, it showed the same article as result.

I used EndnoteX9 ris. file.
This is my ris. file without LB field.

TY  - JOUR
AB  - OBJECTIVE: To assess the sex difference in the prevalence of COVID-19 confirmed cases. DESIGN: Systematic review and meta-analysis. SETTING: PubMed, Cochrane Library and Google Scholar were searched for related information. The authors developed a data extraction form on an Excel sheet and the following data from eligible studies were extracted: author, country, sample size, number of female patients and number of male patients. Using STATA V.14 for analysis, the authors pooled the overall prevalence of men and/or women using a random-effect meta-analysis model. The authors examined the heterogeneity in effect size using Q statistics and I2 statistics. Subgroup and sensitivity analyses were performed. Publication bias was also checked. PARTICIPANTS: Studies on COVID-19 confirmed cases were included. INTERVENTION: Sex (male/female) of COVID-19 confirmed cases was considered. PRIMARY AND SECONDARY OUTCOME MEASURES: The primary outcome was prevalence of COVID-19 among men and women. RESULT(S): A total of 57 studies with 221 195 participants were used in the analysis. The pooled prevalence of COVID-19 among men was found to be 55.00 (51.43-56.58, I2=99.5%, p<0.001). Sensitivity analysis showed the findings were not dependent on a single study. Moreover, a funnel plot showed symmetrical distribution. Egger's regression test p value was not significant, which indicates absence of publication bias in both outcomes. CONCLUSION(S): The prevalence of symptomatic COVID-19 was found to be higher in men than in women. The high prevalence of smoking and alcohol consumption contributed to the high prevalence of COVID-19 among men. Additional studies on the discrepancies in severity and mortality rate due to COVID-19 among men and women and the associated factors are recommended. Copyright © Author(s) (or their employer(s)) 2020. Re-use permitted under CC BY-NC. No commercial re-use. See rights and permissions. Published by BMJ.
AD  - (Abate) Nursing, Woldia University, Amhara, Ethiopia (Kassie, Kassaw, Aragie) Nursing, Woldia University, Amhara, Ethiopia (Masresha) College of Health Sciences, Department of Public Health, Woldia University, Amhara, Ethiopia
AN  - 633136599
AU  - Abate, B. B.
AU  - Kassie, A. M.
AU  - Kassaw, M. W.
AU  - Aragie, T. G.
AU  - Masresha, S. A.
C2  - 061120 Updated search Ovid Medline, Embase, PsychInfo
DA  - 06 Oct
DB  - Embase
DO  - http://dx.doi.org/10.1136/bmjopen-2020-040129
DP  - Ovid Technologies
IS  - 10
KW  - epidemiology
immunology
infectious diseases
adult
alcohol consumption
article
Cochrane Library
communicable disease
coronavirus disease 2019
data extraction
effect size
female
human
male
Medline
meta analysis
mortality rate
outcome assessment
prevalence
publication bias
sample size
sensitivity analysis
sex difference
smoking
systematic review
LA  - English
PY  - 2020
SN  - 2044-6055 (electronic)
2044-6055
SP  - e040129
ST  - Sex difference in coronavirus disease (COVID-19): a systematic review and meta-analysis
T2  - BMJ open
TI  - Sex difference in coronavirus disease (COVID-19): a systematic review and meta-analysis
UR  - http://ezproxy.library.usyd.edu.au/login?url=http://ovidsp.ovid.com/ovidweb.cgi?T=JS&CSC=Y&NEWS=N&PAGE=fulltext&D=emexb&AN=633136599
https://sydney.alma.exlibrisgroup.com/openurl/61USYD_INST/61USYD_INST:sydney?sid=OVID:embase&id=pmid:33028563&id=doi:10.1136%2Fbmjopen-2020-040129&issn=2044-6055&isbn=&volume=10&issue=10&spage=e040129&pages=e040129&date=2020&title=BMJ+open&atitle=Sex+difference+in+coronavirus+disease+%28COVID-19%29%3A+a+systematic+review+and+meta-analysis&aulast=Abate
VL  - 10
ID  - 1108
ER  -

**Comment by SagevdBrand** [comment]
Hi there @Sitong22 ,

Just noticed that you mentioned that this is your .ris file. As you can see there is only one record present in this .ris file, meaning that something might have gone wrong in the export-step from EndNote (see my comment in #754).

Please do let us know whether retrying the export step, while selecting all the records in EndNote, solved (hopefully both of) your issue(s)! 

All the best,
Sofie

**Comment by Rensvandeschoot** [comment]
I am closing this issue because it has been solved with the suggestion of @SagevdBrand . 

@Sitong22 feel free to post a question in our [discussion feed](https://github.com/asreview/asreview/discussions) if you need additional assistance with exporting a `.ris` file from Endnote.
