### ISSUE TITLE
Request for changes to "new project" button

### ISSUE THREAD

**Issue by JTeijema** [asreview/asreview#756]
Hi,

I have a remark regarding the red "new project" button found on the ASReview lab page.

I have found this button to be engaged by both hover and click. By clicking the button, it automatically triggers the hover input too, resulting in the menu opening and then immediatly closing from the click. 

I might be stubborn, but this has happened every time I use the button. The solution would be to have it be either clickable or hover, but not both.

![temp](https://user-images.githubusercontent.com/28191416/134874926-2c625639-3a43-49ce-9782-0b267b627b98.gif)

**Comment by ottomattas** [comment]
Can confirm, happens to me every time as well.

**Comment by J535D165** [comment]
Yes, this is the default behavior of Material UI. I think there are multiple issues reported to material about this. However, I see solutions nowadays on StackOverflow https://stackoverflow.com/questions/61649335/how-do-i-get-material-ui-speeddialaction-onclick-events-to-fire-when-speeddial-i.

**Comment by J535D165** [comment]
@terrymyc do you have time to look into this? Or should we ask @JTeijema ;)

**Comment by terrymyc** [comment]
I plan to replace this speed dial with a floating action button. This change would be related to the refactoring of the project setup screen. At the same time, this issue will be resolved.
