### ISSUE TITLE
pool.json corrupted during screening

### ISSUE THREAD

**Issue by linyuming9** [asreview/asreview#792]
**Describe the bug**
When doing the review, shows "Extra data: line 1 column 43078 (char 43077)" and cannot continue even after restarting the session.

**To Reproduce**
Steps to reproduce the problem: Not Sure.

**Screenshots**
![image](https://user-images.githubusercontent.com/24711064/137112520-e0d98815-5241-44c0-879c-b2e7dd355c6f.png)
![image](https://user-images.githubusercontent.com/24711064/137113621-ad197a88-86ed-49d5-a7d4-1f94eaf8a0b2.png)

**Version information**
 - OS: Windows 10 Pro N for Workstations 21H1
 - ASReview version: 0.17.1

**Additional context**
Dataset is export through Endnote X9. 
The problem might be related to the Chinese/Japanese characters in the dataset.

**Comment by JTeijema** [comment]
Hi @linyuming9 

I've taken a quick look at what could be happening but so far I have found little. Would you be willing to share the dataset? That way I can try to replicate the results and narrow the problem down.

If so, could you send either the dataset or a link to asreview@uu.nl? From there I can continue the search.

Thank you!

**Comment by J535D165** [comment]
Probably a very rare issue with the `lock.json`. CC @PeterLombaers. Hopefully resolved in #688 with the new state file.

**Comment by sebchastin** [comment]
Great fix worked a treat

**Comment by J535D165** [comment]
Resolved in #688
