### ISSUE TITLE
Unique URL for each project

### ISSUE THREAD

**Issue by erikvullings** [asreview/asreview#804]
From an external application, I would like to link to a specific project in the ASreview webapp, without navigating or filtering, so it will open immediately. For example, this could be implemented by adding the filtering arguments to the URL, or by creating a unique link per project.

**Comment by erikvullings** [comment]
@J535D165 Sure, that would work just fine, or perhaps `/projects/{project_id}` and if you just request `/projects`, you get a list of all projects. Preferably documented using [OpenApi](https://swagger.io/specification/).

**Comment by J535D165** [comment]
@terrymyc is this something you would like to work on when you are bored of other stuff? Seems to be straightforward https://www.geeksforgeeks.org/reactjs-router/.

**Comment by J535D165** [comment]
Added in https://github.com/asreview/asreview/pull/983
