### ISSUE TITLE
Corrupt file name results in unclear error

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview#812]
**Describe the bug**
I saved an export file as `asreview-result-anxiety.asreview-screening-RvdS(1).asreview`. When trying to import this file I obtained the following error in the front-end:

![image](https://user-images.githubusercontent.com/36502709/140024365-53a9117f-041e-4872-a4d8-b1e487b899ee.png)

The CMD provided the following information:

```
ValueError: Failed to import project 'asreview-result-anxiety.asreview-screening-RvdS.asreview'.
ERROR:root:Failed to import project 'asreview-result-anxiety.asreview-screening-RvdS.asreview'.
```

The solution was to change the file name into `asreview-result-anxiety.asreview`. 

Apparently, two times `.asreview` in the file name results in an error.

**Version information**
 - OS: Windows
 - ASReview version: 0.18

**Comment by J535D165** [comment]
Looks like this is resolved :)
