### ISSUE TITLE
Importing a CSV file containing initial labeling of records as relevant or irrelevant, instead of manual labeling

### ISSUE THREAD

**Issue by abedicodes** [asreview/asreview#817]
I used your application on its web platform. Based on my understanding, at the first stages of using your application, the user needs to manually label a number of records/papers as relevant/irrelevant, and then these records will be used as (some kind of) training set for the next steps of automatic screening. I have a question about the first stages of manual labeling. Is it possible to read/upload a CSV file (in your Github code or in the web platform) containing the labeled records as the starting point of the next stages?

**Comment by Rensvandeschoot** [comment]
Dear @abedicodes,

There are two options to add prior knowledge:

1. In the front-end you can [manually search](https://github.com/asreview/use-case-FTM/tree/main/data) for (it)relevant papers. The model needs at least 2 labelled records before it can start training: one relevant and one irrelevant record.

2. You can upload a [partly labelled](https://asreview.readthedocs.io/en/latest/features/pre_screening.html?highlight=partly#partly-labeled-data) dataset in which part of the records contain a label (0 or 1) and part of the records are unlabelled. The first set of records will automatically be detected by the software and used as prior knowledge. The second part will be used for the screening phase. In [this table](https://asreview.readthedocs.io/en/latest/intro/datasets.html#id4) you can find the allowed column names containing the labels. 

Hope this helps!

**Comment by abedicodes** [comment]
Excellent! Thanks!
