### ISSUE TITLE
Improve documentation adding a dataset as plug-in

### ISSUE THREAD

**Issue by Rensvandeschoot** [asreview/asreview#858]
The documentation for creating a plug-in that adds a dataset to ASReview can be improved. The current documentation can be found in [readthedocs](https://asreview.readthedocs.io/en/latest/API/extension_dev.html#dataset-extensions) and can be improved by:

- [ ] adding more detailed instructions on how to get started;
- [ ] add list of changes required in the `setup.py`
- [ ] add a working example, see for example the [plug-in](https://github.com/asreview-ftm-hackathon/ASReview-plugin-FTM) we developed during a hackathon;

**Comment by J535D165** [comment]
Marked as stale, might be better to continue conversation in template repo
