### ISSUE TITLE
ASReview version 0.18 cannot handle dataset extensions

### ISSUE THREAD

**Issue by JTeijema** [asreview/asreview#864]
**Describe the bug**
Since version 0.18, the front-end support for extensions is broken. Is is the case for both `asreview.datasets.BaseDataSet` and `asreview.datasets.BaseVersionedDataSet`. 

**To Reproduce**
Steps to reproduce the problem:

Install any type of plugin (like [Covid-19](https://github.com/asreview/asreview-covid19))
Start the frond end
Select the dataset plugin as project dataset

**Screenshots**
![image](https://user-images.githubusercontent.com/28191416/144282063-c4b62112-04a8-40d1-8789-d78264910402.png)

**Version information**
 - OS: Windows
 - ASReview version 0.18

**Comment by terrymyc** [comment]
Duplicate with #830
