### ISSUE TITLE
Problem in the previous knowledge search function

### ISSUE THREAD

**Issue by PeterSchuh** [asreview/asreview#875]
**Describe the bug**
I wanted to set up a new project with previous knowledge. To do this, I tried to search for articles in the database and expected to find the article I was looking for. However, I got an output stating "Failed to load search results". 

**Screenshots**
<img width="865" alt="Screenshot 2021-12-07 at 13 33 21" src="https://user-images.githubusercontent.com/95692192/145029738-dbad9214-c16c-48ec-b9ad-09fc937e2421.png">
.

**Version information**
 - OS: MacOS Version 11.5.2
 - ASReview version 0.17

**Comment by JTeijema** [comment]
Hi! I'd like to help you, but for this I think I will need the asreview file. It can be generated by using the `export this project` option:

![image](https://user-images.githubusercontent.com/28191416/145032219-73c6b764-eb40-4ebf-87a7-daa6f688033b.png)

Alternatively, we can try to share the imported dataset, to replicate the issue on my system that way.

**Comment by JTeijema** [comment]
Hi, it seems the data is not formatted correctly, causing ASReview to find 0 records and thus failing the search. 
The correct format can be found in the [documentation](https://asreview.readthedocs.io/en/latest/intro/datasets.html). 

I took the liberty to format the data. This way, you can start screening directly!

![image](https://user-images.githubusercontent.com/28191416/145035966-0e3e2fb7-f8d2-45d2-9141-5da5d5d7f474.png)

And the link to the new data:
[24112021.transformed.csv](https://github.com/asreview/asreview/files/7668523/24112021.transformed.csv)

Good luck with the screening process. 😄

**Comment by PeterSchuh** [comment]
Wow, thank you so much for the support! I really appreciate that.

**Comment by J535D165** [comment]
Might be similar to #798. Thanks for sharing the dataset, this will help with fixing the issue. 

I think search can't deal with missing title column @terrymyc

**Comment by J535D165** [comment]
![Screenshot 2021-12-08 at 14 09 12](https://user-images.githubusercontent.com/12981139/145213892-c5e837f8-cfc8-4bf4-aee3-1c06ed17979e.png)

@terrymyc there are indeed records, but the title column is missing (see random selection). Search should be able to ignore this, however, this should also be feedback to the user maybe in the dataset upload step.

**Comment by J535D165** [comment]
Partially resolved in #880
