### ISSUE TITLE
Dashboard stats Python API cannot read v0.x project

### ISSUE THREAD

**Issue by terrymyc** [asreview/asreview#877]
If there are projects created in v0.x, the dashboard statistics panel returns the error `Object of type int64 is not JSON serializable`.
The dashboard statistics panel in v1.0 is supposed to be compatible with old projects.

**Comment by J535D165** [comment]
Thanks. Do you have a full traceback?

**Comment by terrymyc** [comment]
![image](https://user-images.githubusercontent.com/17449217/145194554-871b6c03-c681-4ae7-9aad-fbb1af30552a.png)

**Comment by J535D165** [comment]
Might need a test? Why is this not covered?

**Comment by terrymyc** [comment]
@J535D165 Why tag this v0.18?

**Comment by J535D165** [comment]
Mistake from my side.

**Comment by J535D165** [comment]
Fixed in #881
