### ISSUE TITLE
Update the Prepare your data page: Football table depicting extension pathways

### ISSUE THREAD

**Issue by SagevdBrand** [asreview/asreview#879]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The [Prepare your Data page in the RTD ](https://asreview.readthedocs.io/en/latest/intro/datasets.html) is quite long and could use some more clarity. Especially an overview on what type of files is supported and what you can expect from the export functions of ASReview is missing.

**Describe the solution you'd like**
A solution I came up with would be adding a soccer-style-table ⚽ describing which file types and which paths are supported.
Perhaps in the future this could be extended in some way to also incorporate information on which reference managers support which file extensions and thus can be imported to ASReview LAB, but that would become a scary table perhaps 👻.

**Teachability, Documentation, Adoption, Migration Strategy**
See a very ugly, but practical example of what I mean exactly below. For the ASReview case, "Home team" would be "Import to ASReview LAB", and "Away team"  would then be "Export from ASReview LAB".  And in the cells there could be ✔️  or ❌ for example. 
![image](https://user-images.githubusercontent.com/64579032/145214811-a163482e-aa35-427e-8edd-d05bd3de74f9.png)

**Comment by J535D165** [comment]
Fixed, more or less :)
