### ISSUE TITLE
Failed to load statistics

### ISSUE THREAD

**Issue by sebchastin** [asreview/asreview#886]
First of all, Asreview is amazing!
So thanks a lot for this great tool.
I was screening and on loading the next abstract. I got the following message 
"Extra data: line 1 column 81153 (char 81152)" 
THe right colum shows failed to load statistics and so dash the dashboard for this project.
I exported the project and tried to load it on another computer but this did not work either
I tried the simplest thing "RETRY" and restarting everything

![image](https://user-images.githubusercontent.com/95978251/145686274-32f16b27-d0d4-4c4a-8536-0e53ced3ce39.png)
Here is the project export as well just in case this is useful

Many thanks

[seb-screening-hc.zip](https://github.com/asreview/asreview/files/7697477/seb-screening-hc.zip)

**To Reproduce**
Steps to reproduce the problem:

**Screenshots**

**Version information**
 - OS: [e.g. Windows]
 - ASReview version [e.g. 0.6.2]

**Additional context**

**Comment by J535D165** [comment]
Similar issue as #792.

**Comment by sebchastin** [comment]
Thanks a lot this worked a treat


Professor of Health Behaviour Dynamics: People, Places and Systems
Glasgow Caledonian University
School of Health and Life Sciences

***@***.***[2021 awards]
