### ISSUE TITLE
v1.0 project deletion front end request

### ISSUE THREAD

**Issue by JTeijema** [asreview/asreview#890]
## Feature Request
When removing a project in the front end, using version 1.0, the following screen is shown:

![image](https://user-images.githubusercontent.com/28191416/145846672-e212617c-63f6-49c8-9bc8-55a2caec4ed8.png)

I'd personally prefer the github way, which is the following:

![image](https://user-images.githubusercontent.com/28191416/145846805-d14b1bf4-2ba4-49e7-97b3-ce6fdb2e7d9c.png)

This way, when double clicking the word, only the text within the "" is selected, as opposed to the word + a space at the end.

![image](https://user-images.githubusercontent.com/28191416/145846947-cd22f3bd-15bf-424a-a49c-8631c75e1ddd.png)
vs 
![image](https://user-images.githubusercontent.com/28191416/145847012-923f9e90-99d5-4541-a8b6-db00fe1f6e39.png)

**Comment by J535D165** [comment]
Oke agreed. Anyone interested can do a PR.

**Comment by terrymyc** [comment]
I don't agree. We don't expect users to double click to select the project name. Besides, when your project name has more than one word separated by spaces, can you still double-click to select the full project name wrapped by quotation marks?
And I think the current way is consistent with the GitHub way. I don't see quotation marks around a repository name when you try to delete it.

**Comment by terrymyc** [comment]
We had quotation marks around the project name, and I removed them purposely. I can actually double-click to select the name without including the space after it. @JTeijema 

We don't expect users to double click to select the project name. Besides, when your project name has more than one word separated by spaces, can you still double-click to select the full project name wrapped by quotation marks?

And I think the current way is also consistent with the GitHub way. I don't see quotation marks around a repository name when you try to delete the repository.
