### ISSUE TITLE
Argument --n_runs does not work in simulation mode

### ISSUE THREAD

**Issue by brittdev** [asreview/asreview#904]
According to the documentation, you can use the argument --n_runs to indicate the number of runs in a simulation-batch. However, when I use this argument in my command prompt I get this piece of text and error in the prompt:

> usage: simulate-batch [-h] [--embedding EMBEDDING_FP] [--config_file CONFIG_FILE] [--seed SEED]
>                       [--n_prior_included N_PRIOR_INCLUDED] [--n_prior_excluded N_PRIOR_EXCLUDED]
>                       [--prior_idx [PRIOR_IDX ...]] [--prior_record_id [PRIOR_RECORD_ID ...]]
>                       [--included_dataset [INCLUDED_DATASET ...]] [--excluded_dataset [EXCLUDED_DATASET ...]]
>                       [--prior_dataset [PRIOR_DATASET ...]] [--state_file STATE_FILE] [-m MODEL] [-q QUERY_STRATEGY]
>                       [-b BALANCE_STRATEGY] [-e FEATURE_EXTRACTION] [--init_seed INIT_SEED]
>                       [--n_instances N_INSTANCES] [--n_queries N_QUERIES] [-n N_PAPERS] [--verbose VERBOSE] [-r N_RUN]
>                       [dataset ...]
> 
> simulate-batch: error: unrecognized arguments: --n_runs 10
> 

I have upgraded the software to the latest version, but I encountered the same error when using previous versions. 

The argument --n_run does work perfectly fine. This is also the correct argument to use according to the usage message. So I guess this is a mistake in the documentation rather than a bug in the software. 

(My OS is Windows, if that is relevant information).

**Comment by JTeijema** [comment]
Hi! It seems that the documentation is not accurate, and the argument you are looking for is called `--n_run` or `-r`.

Another note, would you prefer `--n_run` or `--n_runs` as argument name? I can change either the argument or the documentation 😄.

**Comment by brittdev** [comment]
> Hi! It seems that the documentation is not accurate, and the argument you are looking for is called `--n_run` or `-r`.
> 
> I will add both `n_run` and `n_runs` to the next version of the software 🙂.

Thanks for the quick response! That sounds like a great solution 🙂

**Comment by J535D165** [comment]
@brittdev thanks for the feedback. 

We are planning to deprecate `simulate-batch` https://github.com/asreview/asreview/pull/835. We think it is straightforward to do a simulation like this yourself with a small bash script. But maybe you have other ideas about this. What do you think about deprecating this feature and what use-cases do you see?

**Comment by brittdev** [comment]
@J535D165 thanks for informing me! I want to assess the performance of different model combinations on my (labeled) datasets and am therefore using simulate-batch in order to account for sampling variance, similar to the simulation study of Ferdinands (2020). I am not familiar with bash programming or other methods that can help me do this faster, so to me, the simulate-batch function is useful because it is the easiest and straightforward method I know. Though I would be interested to know if you have any ideas/suggestions for others like me who have limited knowledge of bash (and Python) programming on how to do a simulation like this myself, or more broadly speaking, how to do a simulation study similar to that of Ferdinands using their own datasets?

**Comment by J535D165** [comment]
@brittdev thanks for your elaborate answer. I assume you are referring to this simulation/file of the study by @GerbrichFerdinands: https://github.com/asreview/paper-simulation-smid-2020-mbr/blob/main/simulation_scripts.sh. 

We are/have been experimenting with a tool to set up and run simulation studies. This tool provides researchers with many more options to simulate performance (compared to the simulate-batch feature). For example, this tool is can simulate all relevant records (instead of random selection). Currently, this tool is for internal use only. We are still improving the tool, documenting it, and we are preparing to make this tool public with the release of version 1 of ASReview LAB (first quarter of 2022). I hope this sounds good to you.
