### ISSUE TITLE
In simulation mode: combination of nn2layer and sbert in single run raises error

### ISSUE THREAD

**Issue by brittdev** [asreview/asreview#905]
In simulation mode, when I try to run a single simulation using the nn-2-layer classifier and sbert feature extraction method, it gives me this error
> ValueError: Error: method 'nn2layer' is not implemented for entry point asreview.models.classifiers.

However, using this combination of classification and feature extraction method in a simulation-batch does not give me the same error. Using the nn-2-layer in combination with the doc2vec feature extraction works fine. 

Currently using ASReview version 0.19. I did not have this issue in version 0.18. My OS is Windows. 

Is this because the nn-2-layer classifier is not compatible with the sbert feature extraction method, or should this combination of methods be able to work just fine and this is a bug?

**Comment by J535D165** [comment]
@JTeijema Any idea?

**Comment by JTeijema** [comment]
Not directly. Could you copy the exact commands you are using to this discussion @brittdev? I'd like to try for myself.

**Comment by brittdev** [comment]
Yes, of course! @JTeijema 

I used the following command:

> asreview simulate [mydataset].csv --state_file [mydataset].h5 --seed 1 -m nn2layer -e sbert --prior_idx 136 68

And this was the output in the prompt:

![image](https://user-images.githubusercontent.com/60607063/147094377-378355c0-6b42-4b82-b6a8-118f31cfaefc.png)

I tried it on a different dataset as well, but then I also got the same error.

**Comment by JTeijema** [comment]
Now I do have a small idea about what the problem is. Could you try to run the command using `nn-2-layer` and not `nn2layer`? 

This does not explain why this issue is not there using the batch simulator though!

**Comment by brittdev** [comment]
Aaah oops, then the problem is definitely a spelling error on my part as it works now and I did use the right command for the simulation batch, so no worries about that. Sorry for the inconvenience!

**Comment by J535D165** [comment]
A more informative error message would help. Somethings like: `Classifier 'nn2layer' not found. Check spelling.`

**Comment by J535D165** [comment]
I'm adding the Help Wanted tag to this issue. Let's keep the issue open.
