### ISSUE TITLE
Change dataset selection typo

### ISSUE THREAD

**Issue by JTeijema** [asreview/asreview#915]
**Describe the bug**
![image](https://user-images.githubusercontent.com/28191416/148937773-f1c129c9-5449-4505-8931-06cc43aab0ed.png)

I think the text contains a typo. Shouldn't it be: 
![image](https://user-images.githubusercontent.com/28191416/148937945-9bc50d00-9254-42a5-a15d-f5bad3e637e2.png)

**Version information**
 - OS: Windows
 - ASReview version 0.19

**Comment by Rensvandeschoot** [comment]
Thanks for the catch! Would you like to de a PR: https://github.com/asreview/asreview/blob/9c55df4239275d40928a3e3177601bafa510aa97/asreview/webapp/src/PreReviewComponents/ProjectUploadFile.js#L89

**Comment by JTeijema** [comment]
> Thanks for the catch! Would you like to de a PR:

Yes!
