### ISSUE TITLE
Importing CSV error

### ISSUE THREAD

**Issue by erikvullings** [asreview/asreview#919]
**Describe the bug**
I've created a new project. When setting up the project, I imported a CSV (using semicolons), and the import generated the following error:

```sh
';' expected after '"'
If the issue remains after retrying, clickhere to report.
```

**To Reproduce**
Import a CSV (see attachment) in which the title contains double quotes, e.g. 

```csv
record_id;title;abstract;keywords;authors;doi;included
444919;"Gescoopt" risico management;;;Jansen, H.J.M.;https://url.com/gescoopt.pdf;
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3140667/149147265-27a5af75-a3bc-4fb0-aa41-af5030ce2bbb.png)

**Version information**
 - OS: Windows 10
 - ASReview version: 0.19

**Additional information**
[test.csv](https://github.com/asreview/asreview/files/7854814/test.csv)

Interestingly, a similar error occurs when the abstract field contains even a single double quote (at the start), but in that case, another error message is generated:

```sh
unexpected end of data
If the issue remains after retrying, click here to report.
```
An example is the following CVS row that triggers this:

```csv
331576;Design collaboration and team working;"One of the core problems ...;;Quanjel, E.M.C.J., Zeiler, W.;;
```

**Comment by J535D165** [comment]
In my opinion, this CSV file is corrupt. Quotation marks should be escaped if part of the cell contents. What did you use to generate this file?

ASReview LAB makes use of `pandas` to read CSV files. Easy to test:

```python
import pandas as pd
pd.read_csv(YOUR_FILE,";")
```

**Comment by erikvullings** [comment]
I did look at the documentation, but could not see any remark about a CSV not being allowed to contain double quotes. Also the error is not very helpful. Could the documentation mention clearly what is and what isn't allowed inside a CSV file (or add a reference to what pandas allows)? And when you talk about escaping quotation marks, I assume that you mean `"?

BTW I needed to create [my own converter](https://github.com/erikvullings/xref2csv) to generate the CSV, since our library uses the XREF XML format.

**Comment by J535D165** [comment]
Closing in on the issue:

```python
import pandas as pd
pd.read_csv("https://github.com/asreview/asreview/files/7854814/test.csv",";")
```

```
   record_id                       title  abstract  ...         authors                           doi included
0     444919  Gescoopt risico management       NaN  ...  Jansen, H.J.M.  https://url.com/gescoopt.pdf      NaN

[1 rows x 7 columns]
```

Guessing the delimiter:

```python
import pandas as pd
pd.read_csv("https://github.com/asreview/asreview/files/7854814/test.csv",None)
```

```
sys:1: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/python_parser.py", line 742, in _next_iter_line
    return next(self.data)
_csv.Error: ';' expected after '"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/python_parser.py", line 146, in __init__
    (index_names, self.orig_names, self.columns) = self._get_index_name(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/python_parser.py", line 872, in _get_index_name
    line = self._next_line()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/python_parser.py", line 681, in _next_line
    orig_line = self._next_iter_line(row_num=self.pos + 1)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/python_parser.py", line 768, in _next_iter_line
    self._alert_malformed(msg, row_num)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/asreview_m1_2/lib/python3.9/site-packages/pandas/io/parsers/python_parser.py", line 722, in _alert_malformed
    raise ParserError(msg)
pandas.errors.ParserError: ';' expected after '"'
```

We can capture parsing errors. 

A more advanced option would be to let the user pick the delimiter.

**Comment by J535D165** [comment]
So guessing delimiters breaks on the quotation. 

I think for your xref2csv, it can implement something like this: https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv#comment45484411_17808731

**Comment by J535D165** [comment]
I think we should capture the parsing error in ASReview (quick fix).

**Comment by J535D165** [comment]
If anyone is interested in implementing the parsing error handler: this might be the place to start

https://github.com/asreview/asreview/blob/1f83efd5244ffee6a73909f2824fd29a88a87bfc/asreview/webapp/api.py#L448-L455

and 

https://github.com/asreview/asreview/blob/1f83efd5244ffee6a73909f2824fd29a88a87bfc/asreview/io/csv_reader.py#L20-L48

A custom error for parsing errors would be ideal I think. (Next to `asreview.exceptions.BadFileFormatError` and `UnicodeError`)

**Comment by bitsgalore** [comment]
The cause of the problem is that the CSV is malformed (opening it in LibreOffice Calc also goes wrong).

From the [CSV format spec](https://www.ietf.org/rfc/rfc4180.txt):

> 6.  Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.

and:

> 7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.

This implies the following changes to the file:

1. Both the "title" and "authors" fields must be wrapped in double quotes (see 6)

2. Since the "title" field includes 2 double quote characters, both characters must be escaped
   by preceding it with an addition double quote character (see 7).

Applying this to your file results in:

```csv
record_id;title;abstract;keywords;authors;doi;included
444919;"""Gescoopt"" risico management";;;"Jansen, H.J.M.";https://url.com/gescoopt.pdf;
```

As a check I tried to validate the resulting file with [CSVLint](https://csvlint.io/). Confusingly, CSVLint complains about an "unexpected whitespace". I suspect this might be a bug in CSVLint, because the
file validates OK if I replace the semicolon delimiters by commas (perhaps CSVLint doesn't identify the
delimiter). The file is also imported correctly in LibreOffice Calc.

**Comment by erikvullings** [comment]
Thanks for the reference: I've updated my output accordingly (fields containing a comma or double quotes are wrapped with double quotes, and existing double quotes are doubled), and now it works without a glitch and double quotes are displayed correctly in ASreview.

@J535D165 and @bitsgalore thanks for your help, closing the issue.
