### ISSUE TITLE
API labeled_stats returns one more labeled count after creating a project

### ISSUE THREAD

**Issue by terrymyc** [asreview/asreview#920]
For example, I labeled two priors when creating a new project; when the model has been trained and the project is ready, `labeled_stats` returns `"n": 3`. It was `"n": 2` before training the model.

**Comment by J535D165** [comment]
@PeterLombaers Interesting :) This can be a lead on why things are failing.

**Comment by PeterLombaers** [comment]
I think this is related to the way the stats are gathered, not the actual number of labeled items. Probably it treats a pending record as already labeled. I can check and fix it later.
