### ISSUE TITLE
ASReview 0.19 .RIS export: last line in note field deleted ?

### ISSUE THREAD

**Issue by J535D165** [asreview/asreview#944]
### Discussed in https://github.com/asreview/asreview/discussions/943

<div type='discussions-op-text'>

<sup>Originally posted by **jaohls** January 27, 2022</sup>
Hi,

Very happy with the RIS export feature of 0.19, but when importing to EN X9 seems like the last line of the "notes" field gets deleted when the "asreview_relevant" (or irrelevant) tag gets added ? Here is side by side comparison of 2 records, before and after processing through ASReview:

![image](https://user-images.githubusercontent.com/96236396/151333887-f18fc908-3052-4e6d-8f18-61efdfa9f810.png)

</div>

**Comment by ottomattas** [comment]
Hi all,

I tried to unsuccessfully replicate the issue. Steps are described below.

1. I separated the record that is shown on the screenshots. I used EndNote 20 and kept only the record in question and one additional record to be able to train a model at a later stage. I then compressed the library:
[ASR_note_debug_record.enlx.zip](https://github.com/asreview/asreview/files/8216451/ASR_note_debug_record.enlx.zip)

2. I exported the record in RIS format, using EndNote 20:
[ASR_note_debug_record.txt](https://github.com/asreview/asreview/files/8216388/ASR_note_debug_record.txt)

3. I checked the notes (N1) field of the record in question in the RIS file:
```
N1  - Using Smart Source Parsing
Agarwal, Sunita
Patodia, Jyoti
Mittal, Jaikrishan
Singh, Yatish
Agnihotri, Vaibhav
Sharma, Varun
```

4. I uploaded the RIS file to ASReview, marked the record in question as irrelevant.
5. I trained the model.
6. I downloaded the results in RIS format:
[asreview_result_944.ris.zip](https://github.com/asreview/asreview/files/8216478/asreview_result_944.ris.zip)

7. I checked the notes (N1) field of the record in question in the RIS file:
```
N1  - Using Smart Source Parsing
N1  - Agarwal, Sunita
N1  - Patodia, Jyoti
N1  - Mittal, Jaikrishan
N1  - Singh, Yatish
N1  - Agnihotri, Vaibhav
N1  - Sharma, Varun
N1  - ASReview_irrelevant
```

8. I imported the RIS file into a clean EndNote library and compressed it for sharing:
[ASR_note_debug_record_asreview.enlx.zip](https://github.com/asreview/asreview/files/8216488/ASR_note_debug_record_asreview.enlx.zip)

9. I compared the notes field of the record in question. I used the library from step 1 and from step 8:
<img width="1512" alt="Screenshot 2022-03-09 at 18 45 22" src="https://user-images.githubusercontent.com/15941300/157489565-bf7ac4e4-9552-4464-ab92-659e4aaccfc3.png">
<img width="1512" alt="Screenshot 2022-03-09 at 18 46 11" src="https://user-images.githubusercontent.com/15941300/157489572-0980a1d6-0e04-4c35-8384-05c3edf5ca5f.png">

10. As it looked valid for me, I just wanted to compare with the record in the library you shared initially:
<img width="1512" alt="Screenshot 2022-03-09 at 18 46 45" src="https://user-images.githubusercontent.com/15941300/157489707-3a342793-8cf1-4675-bda5-8e4ebdb7657e.png">

As everything looks valid and as expected, I am closing this issue for now.
