### ISSUE TITLE
Add place for donation/giving a star on GitHub

### ISSUE THREAD

**Issue by terrymyc** [asreview/asreview#945]
The Donate button in the navigation drawer is going to be replaced somewhere. Perhaps "Follow us on Twitter" and "subscribe to newsletter" also need to find a place.

**Comment by J535D165** [comment]
>The Donate button in the navigation drawer is going to be replaced by a dialog that pops up

I disagree. There should always be a permanent location for this button as well. 

I think it is good to have some discussion with the community on this as well. Maybe they have valuable ideas as well.

**Comment by terrymyc** [comment]
> There should always be a permanent location for this button as well.

Yes, there is a permanent donation button in the Settings dialog.
