### ISSUE TITLE
Documentation contains dead github link on auto-generated pages.

### ISSUE THREAD

**Issue by jteijema** [asreview/asreview#954]
For the auto-generated pages on the readthedocs, the edit on GitHub button is still available but links to a 404 page.

See: https://asreview.readthedocs.io/en/latest/API/generated/asreview.models.base.BaseModel.html 

![image](https://user-images.githubusercontent.com/28191416/151800132-8b7c0cdd-a7b1-4b70-9b24-a44640c2e498.png)

**Comment by J535D165** [comment]
Interested in doing a PR?

**Comment by JTeijema** [comment]
Sounds like that's our solution then @Sync271.

@J535D165 What do you think?
