### ISSUE TITLE
Fail to export the results to RIS file

### ISSUE THREAD

**Issue by TaoRuan-Campus** [asreview/asreview#973]
**Describe the bug**
`'float' object is not iterable`
*What happened? And what did you expect to happen?*

**To Reproduce**

**Screenshots**
<img width="597" alt="Screen Shot 2022-02-10 at 00 51 21" src="https://user-images.githubusercontent.com/55067404/153361639-c2e59526-48e7-4f3c-92e9-267737c5c2d1.png">

**Version information**
 - OS: macOS
 - ASReview version  Latest version

**Additional context**

**Comment by TaoRuan-Campus** [comment]
I guess some data is missing in my original database so there is `nan` value in the results.

**Comment by ottomattas** [comment]
Hello @TaoRuan-Campus. Thanks for opening this issue.

Is it possible for you to share the (full/partial) data set you are trying to use with ASReview?
I can then try replicating the issue and come back with a proper answer and possibly a solution.

**Comment by J535D165** [comment]
Fixed in ASReview v0.19.1. Thanks for reporting.
